### ISSUE TITLE
Oasis restarts issue

### ISSUE THREAD

**Issue by PengyangSong** [esm-tools/esm_tools#901] opened 2023-02-15 12:56 UTC
Dear developers,
ESM_tools seems to always copy the `a2o_flux` and `o2a_flux` files from `restart/oasis3mct/` when doing restart runs. However, these files are links to the latest year oasis restart files (for example, `a2o_flux_21000101-21001231`  and `o2a_flux_21000101-21001231`). This is not correct when we want to do restart from other years (like `2098` or `2099`). 
Therefore, I suggest to always use the proper year file `a2o_flux_*` and `o2a_flux_*` instead of `a2o_flux` and `o2a_flux` in esm_tools restart.
Pengyang

**Comment by chrisdane** [comment] 2023-02-15 17:07
Duplicate of #743, #826, #830 and probably many more undocumented cases.

You need to rename/-link these files by hand.

**Comment by mandresm** [comment] 2023-02-20 21:11
Thanks @chrisdane! @PengyangSong, this is a known problem and probably the more urgent issue. Unfortunately, I really cannot tell you an ETA for a fix...

**Closed as completed** 2023-05-30 07:22 UTC
