### ISSUE TITLE
ERROR: model timestep does not match coupling timestep

### ISSUE THREAD

**Issue by akil-hossain** [esm-tools/esm_tools#369] opened 2021-06-17 13:30 UTC
Hi there,

I am trying to run AWI-ESM2.1 with ECHAM-6.3.05p2, no concurrent radiation. to avoid Model blow up I have reduced step_per_day to 32 in the namelist.config. I got an error message -

```
1385423262851036857
622:  1385423262851036857
775: application called MPI_Abort(MPI_COMM_WORLD, 0) - process 775
622: application called MPI_Abort(MPI_COMM_WORLD, 0) - process 622
654:  1385423262851036857
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
654: application called MPI_Abort(MPI_COMM_WORLD, 0) - process 654
631:  1385423262851036857
```
I have looked into the OASIS code and found this -

```
       do n = 1,prism_ncoupler
          if ((prism_coupler(n)%ltime /= ispval) .and. &
              (sndrcv .and. prism_coupler(n)%sndrcv) .and. &
              (msec >  prism_coupler(n)%ltime + prism_coupler(n)%dt)) then
             write(nulprt,*) subname,' ERROR coupling skipped at earlier time, &
                             & potential deadlock '
             write(nulprt,*) subname,' my coupler = ',cplid,' variable = ',&
                             trim(prism_coupler(cplid)%fldlist)
             write(nulprt,*) subname,' current time = ',msec,' mseclag = ',mseclag
             write(nulprt,*) subname,' skipped coupler = ',n,' variable = ',&
                             trim(prism_coupler(n)%fldlist)
             write(nulprt,*) subname,' skipped coupler last time and dt = ',&
                             prism_coupler(n)%ltime,prism_coupler(n)%dt
             WRITE(nulprt,*) subname,' ERROR model timestep does not match coupling timestep'
             WRITE(nulprt,*) subname,' abort by model :',compid,' proc :',mpi_rank_local
             call oasis_flush(nulprt)
             write(*,*) '1385423262851036857'; call oasis_abort_noarg()
          endif
```

I have used delta_time = 450. which delta_time should match with fesom timesteps 32?

Here is the experiment directory - `/work/ollie/ahossain/micoene/experiments/MIO_boot_w5/`

Best Regards
Akil

**Comment by chrisdane** [comment] 2021-06-18 06:27
Hi Akil

Just to be sure: if you decrease the number of time steps per day, every single time step gets longer, not shorter. To avoid model blow up, normally you want to test a smaller time step, i.e. increase the number of time steps per day.

From my experience you can play with the fesom time step and let the echam time step untouched.

I dont know about the rest, sorry :|

Cheers,
Chris

**Comment by dbarbi** [comment] 2021-07-09 12:53
Hi Akil,
the error message actually says quit clearly what the problem is. You have (at least) three time steps: The fesom time step, the echam time step, and the coupling time step (sometimes more than one coupling time step). 
Now you must understand than for example in fesom, the times between two time steps don't have any meaning. If fesom time step is 1 hour, then the model calculates at times 0, 1h, 2h, ... and nothing can happen in between.
If the coupling time step is actually falling between to time steps of fesom, coupling can not happen. That's what the error says. If in above example the coupling time step is 90 minutes, the first coupling event can't be called.
So, if you change the fesom time step (and chris is right, you actually made it longer), then you need to change the coupling time step as well.

**Comment by akil-hossain** [comment] 2021-07-09 13:58
Thanks, Dirk. Where can I change the coupling time step?

**Comment by akil-hossain** [comment] 2021-07-14 07:18
If I increase step_per_day to 60 or 72, which parameter I should change? 

Thanks
Akil

**Comment by chrisdane** [comment] 2021-07-14 07:22
`namelist.config:&timestep:step_per_day` determines the time step of fesom via `dt = 86400/step_per_day`. If e.g. `step_per_day = 48`, you end up with a time step of 1800 seconds. I dont think that this is your problem.

**Comment by pgierz** [comment] 2021-08-24 13:46
As this is not really an esm-tools problem but rather one for echam/fesom/oasis, I will close this issue to start cleaning up for Version 6. Please re-open if further discussion is needed

**Closed as completed by pgierz** 2021-08-24 13:46 UTC
