### ISSUE TITLE
Changes in xios .xml files ignored

### ISSUE THREAD

**Issue by tsemmler05** [esm-tools/esm_tools#805] opened 2022-08-23 08:44 UTC
When changing the .xml files in the appropriate esm_tools/namelists directory, the changes are ignored and the default .xml files are used instead.

As an example I changed 

/proj/awiiccp5/esm_tools/namelists/oifs/43r3/xios/TCO319_DART/file_def.xml

but in the config file /scratch/awiiccp2/1950c/config/1950c_finished_config.yaml_19030101-19051231 I get the following output - so the file is taken from a hidden directory instead which of course does not include my changes:

    config_sources:
        axis_def: /scratch/awiiccp2/1950c/.venv_esmtools/lib/python3.9/site-packages/esm_tools/namelists/oifs/43r3/xios/TCO319_DART/axis_def.xml
        context_ifs: /scratch/awiiccp2/1950c/.venv_esmtools/lib/python3.9/site-packages/esm_tools/namelists/oifs/43r3/xios/TCO319_DART/context_ifs.xml
        domain_def: /scratch/awiiccp2/1950c/.venv_esmtools/lib/python3.9/site-packages/esm_tools/namelists/oifs/43r3/xios/TCO319_DART/domain_def.xml
        field_def: /scratch/awiiccp2/1950c/.venv_esmtools/lib/python3.9/site-packages/esm_tools/namelists/oifs/43r3/xios/TCO319_DART/field_def.xml
        file_def: /scratch/awiiccp2/1950c/.venv_esmtools/lib/python3.9/site-packages/esm_tools/namelists/oifs/43r3/xios/TCO319_DART/file_def.xml
        grid_def: /scratch/awiiccp2/1950c/.venv_esmtools/lib/python3.9/site-packages/esm_tools/namelists/oifs/43r3/xios/TCO319_DART/grid_def.xml
        io_def: /scratch/awiiccp2/1950c/.venv_esmtools/lib/python3.9/site-packages/esm_tools/namelists/oifs/43r3/xios/TCO319_DART/iodef.xml

I am running on aleph with version 6.13.1. Before I had updated to this esm-tools version (on one of the last days of July) this issue did not exist and I got the following output in /scratch/awiiccp5/1950u/1950u_finished_config.yaml_19010101-19011231:

    config_sources:
        axis_def: /mnt/lustre/proj/awiiccp5/esm_tools/namelists//oifs/43r3/xios/TCO319_DART/axis_def.xml
        context_ifs: /mnt/lustre/proj/awiiccp5/esm_tools/namelists//oifs/43r3/xios/TCO319_DART/context_ifs.xml
        domain_def: /mnt/lustre/proj/awiiccp5/esm_tools/namelists//oifs/43r3/xios/TCO319_DART/domain_def.xml
        field_def: /mnt/lustre/proj/awiiccp5/esm_tools/namelists//oifs/43r3/xios/TCO319_DART/field_def.xml
        file_def: /mnt/lustre/proj/awiiccp5/esm_tools/namelists//oifs/43r3/xios/TCO319_DART/file_def.xml
        grid_def: /mnt/lustre/proj/awiiccp5/esm_tools/namelists//oifs/43r3/xios/TCO319_DART/grid_def.xml
        io_def: /mnt/lustre/proj/awiiccp5/esm_tools/namelists//oifs/43r3/xios/TCO319_DART/iodef.xml

**Comment by JanStreffing** [comment] 2022-08-26 12:04
Hello Tido, was the run `1950c` perhaps done with virtual environment? If so, did `1950u` run with `--open-run`? The virtual environment is mean to protect against these kind of changes to ensure that the namelist defaults and many other defaults stay the same regardless of edits in the esm_tools folder.

I think this could perhaps explain what you see here.

**Comment by tsemmler05** [comment] 2022-08-30 10:11
The run /scratch/awiiccp2/1950c was done by @hegish and yes, I had changed file_def.xml manually in the namelist directory. @hegish, probably you did this run 1950c with virtual environment, i.e. without --open-run?

**Comment by hegish** [comment] 2022-08-30 10:40
I did not create anything in /scratch/awiiccp2/1950c. Is --open-run an esm setting?

**Comment by tsemmler05** [comment] 2022-08-30 13:07
--open-run is an esm setting. Sorry @hegish, it was @JanStreffing. @JanStreffing, did you perform your 1950c run that you started on the 1st of August without --open-run? And, to answer your question about my 1950u simulation: yes, this was run with --open-run and therefore considered my manual changes in file_def.xml.

**Comment by tsemmler05** [comment] 2022-08-30 13:19
Actually, if we know already that this is an esm_tools feature that is in place deliberately we know already the reason why in my case the modified file_def.xml was used and in @JanStreffing case not. Therefore, as soon as you confirm, @JanStreffing, that your 1950c run started on the 1st of August was without --open-run, I can close this issue.

**Comment by JanStreffing** [comment] 2022-08-31 08:10
Yes, as this was intended as the production run I used --contained-run

I also suggest this setting for your final production run, as this ensures that you can freely test for subsequent simulations without affecting the running 1950 control. 

These settings determine whether esm_tools is using the installation in your home dir, or if it reinstalls itself into the work folder and uses a local installation. In the latter case no matter what you do in the esm_tools in your home folder, the work folder installation and the running experiment will be unaffected.

**Comment by tsemmler05** [comment] 2022-08-31 08:21
O.k., thanks for the clarification. I did start yesterday evening the production run with --open-run but I suppose as long as I restart the simulation from now on with --contained-run (in case it crashes) there should not be any problem. When the simulation restarts itself automatically which normally is the case (i.e. as long as it doesn't crash) it anyway will use the same installation.

**Comment by JanStreffing** [comment] 2022-08-31 08:33
I have not switched from --open-run to --closed run during an experiment before. Perhaps @pgierz or @denizural can comment. 
Before you start the contained run, make sure you have committed and pushed all local changes of your esm_tools. In case you don't work on release branch of esm_tools you need to add one more line in the general section of your runscript:

    install_esm_tools_branch: ${name-of-your-branch-on-aleph}

If you work on release this is not necessary, as the esm_tools installed into your experiment folder will default to the latest release version.

**Comment by pgierz** [comment] 2022-08-31 08:38
I’ve also never done that during the simulation before, only at the beginning. Try it out, as far as I know there is nothing obvious which would prevent it from working. 

As to Jan’s second comment: that can either be a branch name, or if you want, a specific commit ID. However, everything needs to be committed, or the changes will not be used on the closed version.

**Comment by JanStreffing** [comment] 2022-09-13 07:37
It was my simulation run with --closed-run.
Case closed, right?

**Closed as completed** 2022-09-13 09:16 UTC
