### ISSUE TITLE
Installing esm_tools on HLRN

### ISSUE THREAD

**Issue by vkolatschek** [esm-tools/esm_tools#903] opened 2023-02-23 17:45 UTC
I installed the esm_tools on HLRN. It seems to have worked, as I can call on esm_master, and esm_tools --version, however I got the following error message:
```
ERROR: flair 0.6.1 requires janome, which is not installed.
ERROR: flair 0.6.1 requires konoha<5.0.0,>=4.0.0, which is not installed.
ERROR: flair 0.6.1 has requirement mpld3==0.3, but you'll have mpld3 0.5.1 which is incompatible.
ERROR: flair 0.6.1 has requirement sentencepiece!=0.1.92, but you'll have sentencepiece 0.1.92 which is incompatible.
```
Will this be a problem, or can I just ignore it? 

**What I did:**
I followed the instructions on the main page.
I added the following to .bashrc:
```
module load git
module load anaconda3

export PATH=$PATH:~/.local/bin
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
And then:
```
$ source ~/.bashrc
$ git clone https://github.com/esm-tools/esm_tools.git
```
And then tried to install:
```
$ cd esm_tools
$ ./install.sh
```
**System info**
 - Supercomputer: HLRN (blogin.hlrn.de)
 - Version: 6.19.5

**Comment by mandresm** [comment] 2023-02-24 07:27
HI @vkolatschek!

Do you get this error while installing? I tried to reproduced it, following your steps in `glogin` but I couldn't.

Can you provide the output of `which esm_tools`?

**Comment by vkolatschek** [comment] 2023-02-24 07:53
Yes, the error message came at the end if the installation process. However it also listed a lot of things that were installed successfully. And it didn't look like it didn't finish.

The output from `which esm_tools` is `~/.local/bin/esm_tools`

**Comment by mandresm** [comment] 2023-02-24 09:44
It seems to me that you are having a conflict on the dependencies. You might have installed another package with dependencies that clash with those of `flair==0.6.1`. As a result `flair` is failing to be installed. I'm not sure which of the dependencies of ESM-Tools depends on `flair` so I cannot estimate if you'll have any problems with your installed ESM-Tools, but if I were you I'd give it a try.

The solution to this type of problem might be to install ESM-Tools in it's own conda environment. Lately I've been playing with many different packages with complex dependencies and I've been using ESM-Tools under conda environments with very good results.

@pgierz, I know that in the long term containers might be the solution, but what do you think about the short term? for example, providing documentation on how to install ESM-Tools and operate them via `conda` to solve this kind of conflicts?

**Comment by pgierz** [comment] 2023-02-24 15:15
Have a look at direnv. It allows you to have a specific separate Python environment based upon your working directory. I've written about it and videoed that: https://awi-esm-handbook.readthedocs.io/en/latest/direnv.html

Containers would of course be the more beautiful solution...

**Comment by mandresm** [comment] 2023-02-24 15:31
Wasn't `direnv` giving problems to people? That's why I started using `conda`

**Comment by pgierz** [comment] 2023-02-24 15:56
No, not that I am aware of, but it does require a bit of set-up work....

**Comment by vkolatschek** [comment] 2023-02-28 09:08
While running FESOM1.4 I now got the following error message. I don't know if it related to the problem while installing the esm-tools. Could this be, or is it something else?
```
/scratch/usr/hbkvtesk/fesom-1.4_output/fesom_spinup/run_19500101-19501231/work/./fesom: 
symbol lookup error: /home/shkifmsw/sw/HPC_libraries/intel2019.0.5_impi2019.5_20200811/lib/libnetcdf.so.15: undefined symbol: H5Pset_all_coll_metadata_ops
```

**Comment by mandresm** [comment] 2023-02-28 11:16
Can you better describe how to reproduce this error? Please, note that FESOM1.4 is not supported on HLRN. We can help making sure it is supported from now on, and it should be easy enough to include its support, but bare in mind it won't run out of the box, it might take us a bit of trial and error. You can check which models are supported where by running `esm_tools --test-state`.

**Comment by vkolatschek** [comment] 2023-02-28 11:25
Oh, I didn't realize that.  I attach my yaml-script. Other than that I just ran 
```
esm_runscripts fesom_spinup_cara.yaml -e fesom_spinup --open-run
```
[fesom_spinup_cara.txt](https://github.com/esm-tools/esm_tools/files/10849662/fesom_spinup_cara.txt)

Compiling fesom worked without any visible/obvious problems.
I'll also attach the log of the attempted run.

[fesom_spinup_fesom_compute_7030685.txt](https://github.com/esm-tools/esm_tools/files/10849715/fesom_spinup_fesom_compute_7030685.txt)

**Comment by mandresm** [comment] 2023-02-28 18:45
Are you running from `blogin` or `glogin`?

**Comment by vkolatschek** [comment] 2023-03-01 09:35
On `blogin`

**Comment by mandresm** [comment] 2023-03-01 12:02
Apologies for the delay. The reasons for it is that HLRN does not have default meshes in the pool for FESOM1 and I am copying those from Levante there. I want to use the default meshes because I don't have permissions to yours, and because in this way I can prepare support for FESOM1 in a more general way and not only adapted to your specific case. Once I have the meshes copied, chances are that I'll be able to reproduce your error and solve it.

**Comment by mandresm** [comment] 2023-03-01 17:31
Hi! I cannot reproduce the error, my fesom1 simulation runs in blogin. Which command have you used to compile the model?

Can you paste here the result of `ldd /scratch/usr/hbkvtesk/fesom-1.4_output/fesom_spinup/run_19500101-19501231/work/./fesom`?

**Comment by vkolatschek** [comment] 2023-03-01 17:55
I just compiled it as usual with `esm_master comp-fesom-1.4`
The result is as follows:
```
ldd /scratch/usr/hbkvtesk/fesom-1.4_output/fesom_spinup/run_19500101-19501231/work/./fesom
	linux-vdso.so.1 =>  (0x00007ffda7703000)
	libnetcdff.so.7 => /sw/dataformats/netcdf/intel.18/4.7.3/skl/lib/libnetcdff.so.7 (0x00002b262f3cc000)
	libnetcdf.so.15 => /sw/dataformats/netcdf/intel.18/4.7.3/skl/lib/libnetcdf.so.15 (0x00002b262f887000)
	libmkl_intel_lp64.so => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so (0x00002b262fbe0000)
	libmkl_intel_thread.so => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so (0x00002b26306f0000)
	libmkl_core.so => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/mkl/lib/intel64_lin/libmkl_core.so (0x00002b2632b1b000)
	libiomp5.so => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/compiler/lib/intel64_lin/libiomp5.so (0x00002b2636b68000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b2636f4b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002b263724d000)
	libnetcdf_c++4.so.1 => /sw/dataformats/netcdf/intel.18/4.7.3/skl/lib/libnetcdf_c++4.so.1 (0x00002b2637451000)
	libmpicxx.so.12 => /sw/comm/impi/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/libmpicxx.so.12 (0x00002b26376a3000)
	libirng.so => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/compiler/lib/intel64_lin/libirng.so (0x00002b26378c3000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00002b2637c37000)
	libcilkrts.so.5 => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/compiler/lib/intel64_lin/libcilkrts.so.5 (0x00002b2637f3f000)
	libmpifort.so.12 => /sw/comm/impi/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/libmpifort.so.12 (0x00002b263817c000)
	libmpi.so.12 => /sw/comm/impi/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/release/libmpi.so.12 (0x00002b263853a000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b263953f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b2639747000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b2639963000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002b2639d31000)
	libhdf5_hl.so.100 => /sw/dataformats/hdf5/intel.18/1.10.5/skl/lib/libhdf5_hl.so.100 (0x00002b2639f47000)
	libhdf5.so.103 => /sw/dataformats/hdf5/intel.18/1.10.5/skl/lib/libhdf5.so.103 (0x00002b263a170000)
	libsz.so.2 => /sw/dataformats/szip/intel.18/2.1.1/skl/lib/libsz.so.2 (0x00002b263a821000)
	libz.so.1 => /lib64/libz.so.1 (0x00002b263aa46000)
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00002b263ac5c000)
	libifport.so.5 => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/compiler/lib/intel64_lin/libifport.so.5 (0x00002b263aec6000)
	libifcoremt.so.5 => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/compiler/lib/intel64_lin/libifcoremt.so.5 (0x00002b263b0f2000)
	libimf.so => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/compiler/lib/intel64_lin/libimf.so (0x00002b263b486000)
	libsvml.so => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/compiler/lib/intel64_lin/libsvml.so (0x00002b263ba19000)
	libintlc.so.5 => /sw/compiler/intel/compilers_and_libraries_2018.6.288/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00002b263d327000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b262f1a8000)
	libfabric.so.1 => /lib64/libfabric.so.1 (0x00002b263d595000)
	libidn.so.11 => /lib64/libidn.so.11 (0x00002b263d8de000)
	libssh2.so.1 => /lib64/libssh2.so.1 (0x00002b263db11000)
	libssl3.so => /lib64/libssl3.so (0x00002b263dd3e000)
	libsmime3.so => /lib64/libsmime3.so (0x00002b263dfa3000)
	libnss3.so => /lib64/libnss3.so (0x00002b263e1cb000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00002b263e505000)
	libplds4.so => /lib64/libplds4.so (0x00002b263e735000)
	libplc4.so => /lib64/libplc4.so (0x00002b263e939000)
	libnspr4.so => /lib64/libnspr4.so (0x00002b263eb3e000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00002b263ed7d000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00002b263efca000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00002b263f2b3000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00002b263f4e6000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00002b263f6ea000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00002b263f8f9000)
	librdmacm.so.1 => /lib64/librdmacm.so.1 (0x00002b263fb4e000)
	libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00002b263fd65000)
	libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00002b263ff7e000)
	libpsm_infinipath.so.1 => /lib64/libpsm_infinipath.so.1 (0x00002b26401eb000)
	libpsm2.so.2 => /lib64/libpsm2.so.2 (0x00002b2640441000)
	libatomic.so.1 => /lib64/libatomic.so.1 (0x00002b26406d5000)
	libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00002b26408dd000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00002b2640afe000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00002b2640d70000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00002b26411d3000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00002b26413e3000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00002b26415e7000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00002b2641801000)
	libinfinipath.so.4 => /lib64/libinfinipath.so.4 (0x00002b2641a1e000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00002b2641c2d000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00002b2641e32000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00002b264203e000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00002b2642265000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00002b264249c000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00002b26426fe000)
```
I also added reading permission to my model directory, the model output directory and my esm_tools directory, in case that helps (hopefully it worked).

Model: `/home/hbkvtesk/fesom-1.4/`
Output: `/scratch/usr/hbkvtesk/fesom-1.4_output/`
esm_tools: `/home/hbkvtesk/esm_tools/`

**Comment by mandresm** [comment] 2023-03-02 20:03
Hi! You can pull now `fix/fesom_hlrn` and give it a try to compile and run.

**Comment by vkolatschek** [comment] 2023-03-03 07:56
Thank you! It's now working.

**Comment by mandresm** [comment] 2023-03-03 07:58
Yey! :) I'll be merging that branch on Monday. Then you can switch back to release and pull, it will be identical to what you have now.

**Comment by vkolatschek** [comment] 2023-03-07 09:03
I just switched back to release and pulled. But maybe there is a wrong path? Because I now get the following output when starting fesom-1.4:
```Module sw.skl loaded.
Module for CMake 3.16.2 loaded.
Module for cdo version 1.9.8 loaded
Contains: cdo suitable for threadsafe (omp) applications.
Module for nco 4.9.1 loaded.
Module for Git 2.21.0 loaded.
Module for Intel Parallel Studio XE Composer Edition (version 2019 Update 5) loaded.
Module for Intel-MPI (version 2019.5) loaded.
183: /scratch/usr/hbkvtesk/fesom-1.4_output/fesom_spinup_test/run_19500101-19501231/work/./fesom: 
error while loading shared libraries: libnetcdff.so.7: cannot open shared object file: No such file or directory

etc.
```

And after recompiling, I'm back to the same error as at the beginning. Did you merge this already to the release branch?

**Comment by mandresm** [comment] 2023-03-07 11:18
It's not yet merged, that's why you are still seeing the same error. Apologies for that. I'll be trying to merge today. I'll let you know when it's done.

**Closed as completed** 2023-03-08 07:34 UTC

**Comment by mandresm** [comment] 2023-03-08 07:35
@vkolatschek, it's now merged into `release`. We support now (have automatic testing implemented) all versions of FESOM in HLRN :)

Feel free to reopen the issue, if you still have problems.
