### ISSUE TITLE
variable expansion in namelist templates

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#95] opened 2020-08-12 07:48 UTC
**BUG**: If I have a yaml runscript that has
```
...
echam:
   restart_rate: 2
   restart_unit: "months"
...
```
and a namelist template (`/esm_tools/namelists/echam/6.3.05p2-foci/PI-CTRL/namelist.echam`) that contains
```
...
&runctl
    dt_start = 1849, 12, 31, 23, 52, 30
    dt_stop = 1880, 12, 31, 23, 52, 30
    putrerun = ${restart_rate}, '${restart_unit}', 'last', 0
    lfractional_mask = .false.
    out_datapath = './'
    out_expname = '${EXP_ID}'
    rerun_filetype = 4
    delta_time = 450
    putdata = 1, 'days', 'last', 0
    trigfiles = 1, 'months', 'first', 0
    nproma = 32
    lcouple = .false.
    getocean = 24, 'steps', 'exact', 0
    putocean = 24, 'steps', 'exact', -450
    lcouple_co2 = .false.
    default_output = .false.
    ltdiag = .true.
    lresume = .false.
/
...
```
namelist.echam is generated, the vars behind `${restart_rate}, ${restart_unit}` are resolved correctly and the resulting namelist in `run_*/work/namelist.echam` is complete EXCEPT for the `&runctl` section which only contains
```
...
&runctl
    dt_start = 1849, 12, 31, 23, 52, 30
    dt_stop = 1850, 6, 30, 23, 52, 30
    putrerun = 2, 'months', 'last', 0
    out_expname = 'focitest201'
    lresume = .false.
    lcouple = .true.
    delta_time = 450
    out_datapath = '/scratch/usr/shkifmsw/esm-experiments//focitest201/run_18500101-18500228/work/'
/
...
```
So the parser does the expansion correctly but seems to choke and and only handle those variables in the `&runctl` block that are dynamic (i.e. `${...}` in the template or modified via a `namelist_changes` entry. All "static" entries from the `runctl` block seem to be omitted.
I get the correct namelist if I replace `putrerun = ${restart_rate}, '${restart_unit}', 'last', 0` with `putrerun = 2, 'months', 'last', 0` in `esm_tools/namelists/echam/6.3.05p2-foci/PI-CTRL/namelist.echam`.
Any ideas?

**Comment by mandresm** [comment] 2020-08-12 08:11
Hi Sebastian,

> I get the correct namelist if I replace `putrerun = ${restart_rate}, '${restart_unit}', 'last', 0` with `putrerun = 2, 'months', 'last', 0` in `esm_tools/namelists/echam/6.3.05p2-foci/PI-CTRL/namelist.echam`.

That is what my suggestion was going to be, to make the default namelist variables not dynamic, and to define anything that you want to define through configuration files using `namelist_changes` or `add_namelist_changes`. I didn't know that you could define variables dynamically in the namelists as I have not seen that done in the models I use to work with, so apparently it can be done but there seems to be a conflict. 

I'm not sure which type of fix this needs (i.e. solving the conflict, or ignoring always dynamic variables in the namelists, or throwing warning...) and probably it also needs to be documented. Let's see if someone else adds to this, otherwise we can bring it up in the next meeting. I hope the provisional solution you found is satisfactory for you in the short term.

**Comment by pgierz** [comment] 2020-09-08 16:11
Hey @seb-wahl, I'm going through the old issues. Is this still a problem or can we close it?

**Comment by seb-wahl** [comment] 2020-09-09 06:57
I need to test it. I'll close it if can't reproduce the bug.

**Comment by dbarbi** [comment] 2020-10-26 14:43
ok, I don't think esm_tools was designed to replace variables in namelists. I also don't think that is what is happening here - in esm_runscripts we replace the variables in the echam.yaml, and the take those to replace entries in namelists we read from templates.
what I think is happening here is that something goes wrong reading the namelist template - e.g. in the putrerun-entry it looks as if '' are missing around the first variable. when that happens the namelist-parser returns an em,pty chapter runctl, into which we then replace the entries from echam.yaml. so that explains why only those that are changed appear in the "finished" namelist, while the rest are missing.

so my assumption is that this is not a esm_tools bug, but a buggy namelist-template. maybe correcting the template will solve it. I can have a look.

**Comment by nwieters** [comment] 2020-12-03 10:15
I tried to reconstruct the issue and found that the namelist template you mentioned doesn't have these dynamic variables for `${restart_rate}` and `${restart_unit}` anymore (release branch of version 5.0.0):
```
&runctl
    dt_start = 1849, 12, 31, 23, 52, 30
    dt_stop = 1880, 12, 31, 23, 52, 30
    putrerun = 12, 'months', 'last', 0
    lfractional_mask = .false.
    out_datapath = './'
    out_expname = '${EXP_ID}'
    rerun_filetype = 4
    delta_time = 450
    putdata = 1, 'days', 'last', 0
    trigfiles = 1, 'months', 'first', 0
    nproma = 32
    lcouple = .false.
    getocean = 24, 'steps', 'exact', 0
    putocean = 24, 'steps', 'exact', -450
    lcouple_co2 = .false.
    default_output = .false.
    ltdiag = .true.
    lresume = .false.
/
```

I did a test with setting
```
echam:
    restart_rate: 2
    restart_unit: "months"
```
and the resulting line in the echam namelist is
`putrerun = 2, 'months', 'first', 0`

I also tried to set this via a `namelist_changes `in my runscrript:
```
echam:
     namelist_changes:
         namelist.echam:
             runctl:
                 putrerun: 3, months, first, 0
     restart_rate: 2
     restart_unit: "months"
```
This will result in the namelist entry
`putrerun = '3, months, first, 0'`
I don't know right away if this is a valid entry for echam. But it shows that `namelist_changes` wins over setting the variables `restart_rate` and `restart_unit`.

@seb-wahl I think what you tried to do now works, since the namelist template has been already fixed in the last release.

Maybe we would need a documented list of variables that, if set, do changes to a namelist even without putting a `namelist_changes` part in your runscript.

**Comment by nwieters** [comment] 2020-12-03 10:20
Can someone explain how you can set this correctly in a runcript:
```
echam:
     namelist_changes:
         namelist.echam:
             runctl:
                 putrerun: 3, months, first, 0
```
Should result in 
`putrerun = 3, 'months', 'first', 0`

not

`putrerun = '3, months, first, 0'`

**Comment by mandresm** [comment] 2020-12-03 10:57
have you tried `putrerun: "3, 'months', 'first', 0"`?

I think that having vars called from the namelist is not a good idea. I would personally prefer to see all the changes in the namelist occuring in namelist_changes, in this way unnecessary potential conflicts are avoided and we only need to instruct the user once about how to do this. Can anyone report a case in which having variables called directly from the namelist would be benefitial?

**Comment by nwieters** [comment] 2020-12-03 11:03
I don't mean to have variables in the namelist. And I am not sure whether this is just an old thing that remained from the old bash version? As placeholders, not sure.

But there are runscript variables that you can set (like 
echam:
    restart_rate: 2
    restart_unit: "months"

that change a namelist. And I guess there are more variabels that do this (or?).

**Comment by pgierz** [comment] 2020-12-03 11:06
make it a list. Then it will work. See also the f90nml docs: https://f90nml.readthedocs.io/en/latest/index.html

You need:
```yaml
purerun:
   - 3
   - months
   - first
   - 0
```
or
```yaml
putrerun: [3, 'months', 'first', 0]
```

The example of the docs is "layout"
```fortran
&config_nml
   input = 'wind.nc'
   steps = 864
   layout = 8, 16
   visc = 1.0e-4
   use_biharmonic = .false.
/
```
becomes:
```python
nml = {
    'config_nml': {
        'input': 'wind.nc',
        'steps': 864,
        'layout': [8, 16],
        'visc': 0.0001,
        'use_biharmonic': False
    }
}
```

**Comment by seb-wahl** [comment] 2020-12-03 11:24
I think if all the namelist templates are checked for "illegal" statements ${...} entries and "repaired" accordingly, we can close the issue. But I'm not sure if it will work for all variables, e.g. `${EXP_ID}`?
Thanks for following up on this and especially thanks to @pgierz for pointing to the f90nml documentation.

**Comment by nwieters** [comment] 2020-12-03 12:18
But are these ${} statements evaluated by anything (e.g. esm_parser)? Or are they just strings?

**Comment by nwieters** [comment] 2020-12-03 13:17
I (not knowning) tested with a namelist for echam that doesn't have any ${} in it, not even ${EXP_ID}. I think these 'variables' do nothing (except causing @seb-wahl problem). I will replace these statements in all namelist with default/fill values.

**Comment by nwieters** [comment] 2020-12-03 14:28
In case of echam namelists these ${} are removed now. In other "namelist" I think these are real shell variables.
Can we close this issue now?

**Comment by dbarbi** [comment] 2020-12-03 14:30
closed

**Closed as completed by dbarbi** 2020-12-03 14:30 UTC
Labels: bug
