### ISSUE TITLE
branch off experiment

### ISSUE THREAD

**Issue by tsemmler05** [esm-tools/esm_tools#891] opened 2023-01-20 08:37 UTC
I try to branch off an experiment. I specified the location of the restart files and set lresume to .true. for both OpenIFS and FESOM2. The esm run script asks me for specification of prev_run_config_file. I specified this:

    prev_run_config_file: '/scratch/awiiccp5/sp1850c/config/'

and get an error:

 ERROR: 'prev_run_config_file' incorrectly defined
-------------------------------------------------
The file defined in the 'oifs.prev_run_config_path' (/scratch/awiiccp5/sp1850c/config/) does not exist.

I also tried to give the file name of the config file: /scratch/awiiccp5/sp1850c/config/sp1850c_finished_config.yaml_18400101-18491231

How is it meant to be specified? I didn't find it in the readthedocs.

I updated esm_tools on 18th of January. esm_versions check does not give a result so I can't tell you esm_version number. I am running on aleph.

You can find the run script here:

/proj/awiicp5/awicm3-frontiers-xios-aleph-TCO95L91-CORE2-hi1850c.yaml

**Comment by pgierz** [comment] 2023-01-20 13:56
The solution that Tido and I just came up with is that this should point to the exact file, and also contain `ini_parent_*` variables for each component in the model. @mandresm, you implemented previous run, if you can confirm this, we can then update the handbook accordingly

**Comment by pgierz** [comment] 2023-01-20 13:56
sorry, didn't mean to close the issue, wrong button ;-)

**Comment by mandresm** [comment] 2023-01-31 13:18
I can confirm that: you need to manually specify the file if you are branching off an experiment. The reason for that is that doing automatically poses this problems depending on the approach you go for:
1. Get the last run file. That's okay as long as you don't want to branch off from the middle of a run.
2. Guess the name of the file based on the current date of the branchoff experiment. That's also limiting for example because the parent experiment could have different run lengths (yearly restarts), while the branchoff experiment could be run with monthly restarts. Then the branchoff experiment cannot know the first date in the `finished_config.yaml` oif the parent experiment. 

In order to keep things simple, save and sound one needs to tell ESM-Tools which file should be using, so the solution by @pgierz is the correct one.

I'll add a note in the documentation of `prev_run` (https://esm-tools.readthedocs.io/en/latest/yaml.html?highlight=prev_run#accessing-variables-from-the-previous-run-prev-run) and then close this issue.

**Closed as completed** 2023-01-31 14:40 UTC
