### ISSUE TITLE
esm_master get-awiesm3-v3.4 gives no feedback

### ISSUE THREAD

**Issue by hajlaci** [esm-tools/esm_tools#1230] opened 2024-10-14 12:24 UTC
@JanStreffing and I implemented https://github.com/esm-tools/esm_tools/tree/feat/awiesm3-v3.4
The command
`esm_master get-awiesm3-v3.4`
results in an empty response. Esm master seemingly finishes the command without anything being done. Nothing is listed for download, nothing is downloaded. We tested this on levante. esm_master without any model does list awiesm3-v3.4 and the get command as available.

Here is what a wrong version will look like
```
esm_master get-awiesm3-v3.5

No targets found for keyword awiesm3-v3.5. Type 'esm_master' to get a full list
of available targets.
```

**Comment by mandresm** [comment] 2024-10-21 14:50
So ESM-Tools is not reporting an error, and simply exiting. We will fix that in a new merge request.

The problem is that the grids for the LPG-GUESS coupling fields are not defined. Here you are mapping fields from LPG-GUESS to OpenIFS:
https://github.com/esm-tools/esm_tools/blob/b7944cfe268befe7b8f612830319a783625079e8/configs/setups/awiesm3/awiesm3.yaml#L390-L397

However, you have not defined grids for these fields, and without that oasis and `oasis.py` cannot work. You have partially already done that here:
https://github.com/esm-tools/esm_tools/blob/b7944cfe268befe7b8f612830319a783625079e8/configs/setups/awiesm3/awiesm3.yaml#L153-L159

In principle all you need to do is to change the TODO by the list of fields in `oifs` related to this new coupling, and do the same for `lpg_guess` for its fields as well.

**Comment by mandresm** [comment] 2024-10-21 15:18
Note that this is a problem that should not need to pop-up during `esm_master` since it should only take care of the compilation part and not care about the coupling part, which belongs to `esm_runscripts`. So, if you want a workaround for now and deal with the problem later on when you are working on running the coupled version, simply comments these lines:
https://github.com/esm-tools/esm_tools/blob/b7944cfe268befe7b8f612830319a783625079e8/configs/setups/awiesm3/awiesm3.yaml#L390-L397

**Comment by pgierz** [comment] 2024-10-21 15:43
> Note that this is a problem that should not need to pop-up during esm_master

So now I have another one to add to my box of reasons why `esm_master` is badly designed internally. See #1237

**Comment by mandresm** [comment] 2024-10-21 16:09
Hi @hajlaci and @JanStreffing, I have pushed a fix to your branch. It does not solve the problem but at least now you'll get the error. The reason why you were not seen the error before was because the logger was broken, and now it is fixed.

**Comment by JanStreffing** [comment] 2024-12-10 11:00
works

**Closed as completed by JanStreffing** 2024-12-10 11:00 UTC
Labels: bug, error handling
