### ISSUE TITLE
Slow job submission with ESM-tools

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#1073] opened 2023-10-18 07:52 UTC
An email from @mathanase 

> Miguel,
>
> Lately, I have been experiencing particularly long submission times for my jobs (day-long AWI-CM-1 runs).
> I contacted DKRZ support, but they are unable to provide insights since the job submissions are done with ESM tools. 
> So I was hoping you might be able to enlighten me...
>
> I asked around, and it seems Antonio does not have the same issue. So I suppose this may be related to my jobs, but I do not > understand what, as these submissions used to be much faster for me. 
>
> The jobs I have issues with are e.g.:
>
> esm_runscripts /home/a/a270216/NRT/ERA5T_ENSEMBLE/runscripts/awicm1_T127L95_PI_T20_24H_20230922/awicm1_T127L95_PI_T20_24H_20230922_E1.yaml -e awicm1_T127L95_PI_T20_24H_20230922_E1 -v --open-run
>
> It can take from several minutes to 20-30 min between executing the command line and seeing the run actually submitted & pending in the queue. 
>
> Do you know what could be causing this?

**Comment by mandresm** [comment] 2023-10-18 07:59
I've heard the rumors from DKRZ support team already :p

> It can take from several minutes to 20-30 min between executing the command line and seeing the run actually submitted & pending in the queue.

That is insane! Do you know at which point is getting slow?

How often can you reproduce this behavior?

I have time to look at this tomorrow.

Kind regards,
Miguel

**Comment by mathanase** [comment] 2023-10-18 08:09
Hahaha, sorry that you are getting whispers because of my issues again!


I know that it gets stuck when reading the ocean restart files.


I have not tried too hard to reproduce it, but on Monday for example I had a routine submitting 15 of these jobs in a row, and it timed out after 8h (yes!) because of the job submission step...

So it has happened at least 15 times.


Thanks, Miguel, and I'll be at AWI tomorrow in case you would need me to stop by.


Cheers

Marylou


________________________________

**Comment by mandresm** [comment] 2023-10-18 08:23
I don't have the right permissions to this folder `/home/a/a270216/NRT/ERA5T_ENSEMBLE/runscripts/awicm1_T127L95_PI_T20_24H_20230922`

But I don't need permissions there, if you pointed me at the failed-experiment folder I can at least have a fast look at it.

**Comment by mathanase** [comment] 2023-10-18 08:36
Well, the experiments did not fail, the one that ended up being submitted after long minutes ran successfully.


So that's why it is difficult to see what is going wrong.

I copied the log file of the routine that failed due to time limit in my work folder:


/work/ba1264/a270216/NRT/tmp/invoke_NRT_storyline_AWICM1_weakndg.out


Thanks Miguel

________________________________

**Comment by chrisdane** [comment] 2023-10-18 09:56
Hi

Based on your description its not clear to me what exactly takes so much time. The `esm_runscripts` command, being in the queue, or the actual `srun` command? 

Just one piece of info: Some time ago DKRZ said that adding the number of nodes explicitly to the jobscript may reduce queue time significantly. When this was announced, I added
```
computer:
    additional_flags: "--nodes=10"
```
to the runscript and indeed, queue time reduced significantly. But this is some time ago and I would assume that DKRZ solved that issue already.

Cheers,
Chris

**Comment by mathanase** [comment] 2023-10-18 10:16
What takes a lot of time is the  esm_runscripts command.

Using the flag -v I was able to see that the command gets stuck for a very long time at the stage that copies the ocean restart files.


Thanks for the tip on the queue, although it will (I suppose) not solve my command issue :)


________________________________

**Comment by mandresm** [comment] 2023-10-19 08:30
computer:
    additional_flags: "--nodes=10"
    
That above has the potential to interfere with other flags generated automatically with ESM-Tools, so I would discourage it's use, unless queueing at DKRZ is still affected. In that case we would need to change something within ESM-Tools to also request the number of nodes.

About copying the files of fesom, which files are the once that are taking forever? Which version of ESM-Tools and AWICM1?

**Comment by mathanase** [comment] 2023-10-19 09:06
I am using ESM tools version 6.21.5, and I run the cmip6 AWICM1 configuration (see model codes in /work/ab0995/a270148/ESMTOOLS10August2022/esm_tools/awicm-CMIP6/).

Note that I was using the same ESM tools and model version before, and things were running smoothly. 

The file that takes forever to be copied is "oce_restart". I just did a test submission now with the verbose flag, and it took **28 minutes** to copy that single file before finally allowing the job to be submitted. Needless to say, it is not sustainable...

**Comment by mandresm** [comment] 2023-10-19 09:32
@nwieters, @mathanase and myself are looking into this right now

**Comment by mathanase** [comment] 2023-10-20 08:33
For the record, @mandresm @antoniofis10000 and I found the source of the issue: within one calendar year, fesom ocean restart files accumulate the restart fields from all previous "parent restarts". 

The simulations we are doing (for the near-real-time storyline system) require daily restarts, meaning, after ~4 months my fesom restart files have accumulated 120 days of restart fields, making them very heavy. This slows down the copying during the esm_runscripts command, but also massively slows down the reading time during the actual day-long runs. 

I am working on a fix now to incorporate into my main bash routine, to "clean up" the unnecessary restart fields except for the last model day.

**Comment by mandresm** [comment] 2023-10-25 11:31
This is not and strictly ESM-Tools related issue, and it seems to be solved, so can we proceed to close it @mathanase ?

**Comment by JanStreffing** [comment] 2023-10-26 16:27
They way forward would be to have FESOM write into different files than it reads from. It already does that at the change of the year. Marylou would need this at the change of each day. So you would need the filename that FESOM reads and writes into to change in the FORTRAN code.

**Comment by nwieters** [comment] 2023-11-08 15:06
Dear @mathanase ,
from the comments I understand that this is not an issue caused directly by ESM-Tools. Therefore, I will close this issue for now.

**Closed as completed by nwieters** 2023-11-08 15:06 UTC
Labels: levante, help
