### ISSUE TITLE
esm_runscripts -c has become invasive

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#169] opened 2020-10-21 08:06 UTC
**Describe the bug**
When using the check switch of esm_runscripts the whole simulation preparation process will be executed but no job submission takes place. Per design that switch should be non-invasive, i.e. after running esm_runscripts -e X -c I should be able to run esm_runscripts -e X and get identical results as if I had not run the command with the check switch before. Yet, currently this seems not to be the case.

**To Reproduce**
In a particular case I found that after running esm_runscripts with the -c switch for a fresh simulation (i.e. the simulation folder did not yet exists), in namelist.echam the rerun switch was initialized to, as expected, lresume = .false. After running the same command again, without the -c switch, suddenly the rerun switch was initialized with .true., i.e. the simulation would initialize from a previous restart. This is not the expected behavior as no first year was simulated yet, and no such restart file exists. According to @pgierz this could be related to generation of a date file in the "-c" iteration of esm_runscripts, which then leads to a different behavior in the real submission iteration of esm_runscripts. Currently, this needs to be overcome by manually deleting the simulation folder after an "esm_runscripts -c" which is probably against the philosophy of the -c switch.

**Expected behavior**
esm_runscripts -c should not have any impact on any further executions of esm_runscripts for any given simulation.

**Screenshots**
Does not apply.

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.3
esm_parser: 4.2.2
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1
esm_tools: 4.2.8 (development install, on branch: release, describe=v4.2.8-8-g37897af-dirty)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.6.0

**Additional context**
Does not apply.

**Comment by pgierz** [comment] 2020-10-21 09:10
Hi Christian,

I am unable to reproduce that. It might have been linked to the messy installation we cleaned up together. With a clean install:
```
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.3
esm_parser: 4.2.2
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1 (development install, on branch: release, describe=v4.2.1)
esm_tools: 4.2.9 (development install, on branch: release, describe=v4.2.9)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.6.0
```
First time in check mode:
```
$ esm_runscripts PI_ctrl_awiesm-2.1_LR_mistral_annual_restarts_default_output_PG_test001.yaml -e check_test -c
```
`lresume` is 0 as expected. Second time:
```
$ esm_runscripts PI_ctrl_awiesm-2.1_LR_mistral_annual_restarts_default_output_PG_test001.yaml -e check_test
```
`lresume` is still 0, as expected.

I will close this for now. Please re-open if this happens again.

**Closed as completed by pgierz** 2020-10-21 09:10 UTC
