### ISSUE TITLE
FESOM-1.4 with ice shelf cavities after compiling not working anymore

### ISSUE THREAD

**Issue by vkolatschek** [esm-tools/esm_tools#750] opened 2022-07-27 08:48 UTC
**Describe the problem you are facing**
I am trying to run fesom-1.4 with cavities on Levante. And I have two versions of the model code I'm using. One was compiled on 31 May, the other this week. The problem is that the old version is working, but the new version produces NaNs in the ice shelf cavity and along -180/180 longitude.  

**To Reproduce**
Take `/home/a/a270147/fesom-1.4_depthlayerproblem/` (working version)
and recompile it. Then it doesn't work anymore.

**Runscripts and other relevant files**
Model:  `/home/a/a270147/fesom-1.4_depthlayerproblem/`
Compile with: `/home/a/a270147/comp-fesom-1.4_script_depthlayerproblem.sh`
Runscript: `/home/a/a270147/fesom_runscripts/fesom-levante_RGLOBI_cold.yaml`

**System:**
 - Supercomputer: Levante
 - Version: esm_tools, version 6.7.1

**Additional context**
A working version is good to have, however this one does not yet include the optimizations that were done for levante. Because of that fesom is very slow. I would need to recompile the model to include the changes in the CMakeLists.txt files.

**Comment by vkolatschek** [comment] 2022-08-09 08:52
I found the reason why I had one working version of the compiled model from March, and the not-working, newer compilation. After some trials and help from the dkrz support, we figured out, that FESOM1.4 with ice shelf cavities apparently does not work when the flag `use_sw_pene` is ON. 

Has this problem been documented before?

**Comment by nwieters** [comment] 2023-07-27 10:02
I will close this issue here since it seams to be solved by @vkolatschek and it is not directly related/caused by an error in the esm_tools but rather to namelist entry problem that is specific to a certain model used.

**Closed as completed** 2023-07-27 10:03 UTC
