### ISSUE TITLE
Error handeling in case of empty yaml block.

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#484] opened 2021-10-22 09:32 UTC
This error handling was a bit confusing while setting up oifsamip setup.
I erroneously added an empty block for the amip component to my first runscript, thinking that it would be good to show other users that the possibility to add custom amip options exists. Even though I did not have any right now. 
```
amip:

```
This is not correct yaml syntax. However instead of getting an error about wrong yaml syntax, I got one about `user_config["general"]["setup_name"] ` does not exist

```
(Pdb) c
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 1: general:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 4: general:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 5: user:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 6: setup_name:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 7: version:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 8: compute_time:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 9: initial_date:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 10: final_date:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 11: /work/ollie/${user}/runtime/${general.setup_name}-${general.version}/: bad substitution
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 12: nday:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 13: nmonth:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 14: nyear:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 16: computer:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 17: heterogeneous_parallelization:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 19: oifsamip:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 20: postprocessing:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 21: /home/ollie/${user}/model_codes/${general.setup_name}-${general.version}/: bad substitution
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 23: amip:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 25: oifs:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 26: resolution:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 27: levels:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 28: prepifs_expid:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 29: input_expid:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 30: wam:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 31: lresume:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 32: time_step:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 33: nproc:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 34: omp_num_threads:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 36: oasis3mct:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 37: lresume:: command not found
/home/ollie/jstreffi/esm_tools/runscripts/oifsamip/cleaned_runscript: line 38: time_step:: command not found
Traceback (most recent call last):
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/ollie/jstreffi/.local/bin/esm_runscripts", line 3, in <module>
    import re
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/cli.py", line 221, in main
    Setup = SimulationSetup(command_line_config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 31, in __init__
    self.get_total_config_from_user_config(user_config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 153, in get_total_config_from_user_config
    setup_name = user_config["general"]["setup_name"]
KeyError: 'setup_name'
```

The fix was simple, just remove the block or add something into it, but I do think that more people unfamiliar with yaml might stumble over this.

**Comment by mandresm** [comment] 2021-10-22 09:33
Thanks @JanStreffing, I'll work on this throughout the day.

**Comment by mandresm** [comment] 2021-10-27 10:02
Fixes took place on `prep_release` branches of `esm_rusncripts` and `esm_parser`, and it'll be part of release 6.0.

Now it displays the following message when a component is empty in a yaml file:
```
ERROR: YAML syntax
------------------
The component amip is empty in the file /mnt/lustre01/pf/a/a270152/my_scripts/test.yaml. ESM-Tools does not support empty components, either add some variables to the amip section, or remove it from this file.
```

**Comment by mandresm** [comment] 2021-10-27 10:20
I was to fast to closing the issue, there are problems with the fix. I reverted the fix to a status where things where working, and I'll make it work later.

**Comment by denizural** [comment] 2021-10-28 12:45
I am writing a fix for this error which will also serve as a feature.

**Comment by nwieters** [comment] 2023-08-03 10:11
I think I was able to reproduce this issue, although with a different error message.
I will look into this and implement a better exception handling for this with a clearer error message.

**Comment by nwieters** [comment] 2023-08-03 12:26
@mandresm why have you reverted your commit? Was there a general problem with your solution? Otherwise I would reactivate the call for check_for_empty_components?

**Comment by mandresm** [comment] 2023-08-04 16:27
I do not remember what the problem was. Sure, reactivate the call. If you see room for improvements also go for it :)

**Comment by nwieters** [comment] 2023-08-18 08:31
I think I found the reason why you reverted your solution.
esm_master will now complain at some variables that need to be set to "".

I'm trying to refine your function to be sensitive for "", if this is possible.

**Closed as completed** 2023-08-28 10:27 UTC
Labels: error handling
