### ISSUE TITLE
FYI: new python module on ollie python3/3.7.7_intel2020u2 won't install tools: Unable to get the locale encoding

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#124] opened 2020-09-07 08:54 UTC
With the new release of the esm-tools out the door I wanted to see where things are at. I downloaded the tools anew on ollie:

```
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 3.0.0 (development install, on branch: release, describe=v3.0.0)
esm_master: 4.1.2
esm_parser: 4.1.2
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.1.5
esm_tools: 4.1.9 (development install, on branch: release, describe=v4.1.5-40-g07f82fc)
esm_plugin_manager: 4.0.0
esm_version_checker: 4.4.0
```

I tried installing with the soon to be default python3/3.7.7_intel2020u2 and got the following error:

```
./install.sh 
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fb763498740 (most recent call first):
./install.sh: line 25: 100158 Aborted                 (core dumped) pip install --user -e .
```

I then tried it with python3/3.6.5_intel2019(default) and it worked without a problem. I thought I raise the awareness for this before python3/3.7.7_intel2020u2 becomes the default. Maybe you get in touch with Natalja Rackowsky.

Cheers, Jan

**Comment by pgierz** [comment] 2020-09-09 08:35
Hey Jan,

I can't reproduce this. For me, the following works on ollie:

```
$ module purge
$ module load python3/3.7.7_intel2020u2
$ module load git
$ git clone https://github.com/esm-tools/esm_tools.git
$ cd esm_tools
$ ./install.sh 
```
then:
```
$ esm_versions check
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.1.1
esm_master: 4.2.1
esm_parser: 4.1.2
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.1.5
esm_tools: 4.2.0 (development install, on branch: release, describe=v4.2.0)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.4.0
```

As a note to @denizural and @mandresm: did you guys push the tags for esm_parser, esm_envrironment, and esm_runscripts? Either I deleted my old version incorrectly, or something is going wrong with the install...

**Comment by pgierz** [comment] 2020-10-09 11:16
I checked again this morning, and this no longer seems to be happening (at least, in my environment). I'm closing this for now. Feel free to re-open if it appears again.

**Closed as completed by pgierz** 2020-10-09 11:16 UTC
