### ISSUE TITLE
model bin not updated on esm_runscripts -U -update

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#513] opened 2021-12-02 09:29 UTC
**Describe the bug**
Continuing a run with `esm_runscripts runscript -e expname -U` updates the esm-* files but not the - potentially changed - model binaries.

**To Reproduce**
Stop a run. Recompile the model. Continue the run with `esm_runscripts runscript -e expname -U -c`. The experiment will continue with the old model binaries.

**Expected behavior**
The new model binaries should be used when submitted with `-U`. 

Alternatively I would like to use another argument to explicitly update the model bins, e.g. `-update_bin`, as I also see good reasons to not update the model bins on `-U`.  

**System (please complete the following information):**
 - Supercomputer: mistral
<details>
<summary>esm_versions check</summary>

```
+---------------------+-----------+---------------------------------------------------------------+----------------------+----------------------------+
| package_name        | version   | file                                                          | branch               | tags                       |
|---------------------+-----------+---------------------------------------------------------------+----------------------+----------------------------|
| esm_analysis        | 0.3.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_archiving       | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_calendar        | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_database        | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_environment     | 5.1.3     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_master          | 5.1.6     | /mnt/lustre01/pf/a/a270073/esm/src/esm_master                 | develop              | v5.1.6-10-g96c2b66         |
| esm_motd            | 5.0.2     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_parser          | 5.1.12    | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_plugin_manager  | 5.0.1     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_profile         | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_rcfile          | 5.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
| esm_runscripts      | 5.1.35    | /mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts             | hist_fixed_issue_485 | v5.1.35-4-g5154c21         |
| esm_tools           | 5.1.0     | /mnt/lustre01/pf/a/a270073/esm/esm_tools                      | ssp585_awicm-recom   | v5.0.17-89-g2ad1cfd4-dirty |
| esm_version_checker | 5.1.5     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                      |                            |
+---------------------+-----------+---------------------------------------------------------------+----------------------+----------------------------+
```
</details>

**Comment by mandresm** [comment] 2021-12-02 18:37
This will be solved in version 6. We have stop making changes to release 5.

**Comment by mandresm** [comment] 2021-12-15 06:26
This functionality has been fully developed and integrated by now into what is going to be release 6.0. Therefore, I think we can now close this issue.

**Comment by chrisdane** [comment] 2023-01-04 09:27
Not working with
```
version = esm_tools, version 6.18.5
branch  = release
hash    = 8c826c1b
src     = /home/a/a270073/esm/esm_tools (levante3.lvt.dkrz.de)
```

If the directory `.venv_esmtools/` exists, `esm_runscripts -U` still has no effect on the model binaries, the old already existing binaries are used.

If the directory `.venv_esmtools/` does not exist, `esm_runscripts -U` says
```
Could not copy <base_dir>/<runid>/bin/echam/echam6 to <base_dir>/<runid>/run_<timestamp>/bin/echam/echam6 for unknown reason.
```
and later
```
- missing source: <base_dir>/<runid>/bin/echam/echam6
- missing target: <base_dir>/<runid>/run_<timestamp>/bin/echam/echam6
```
Of course, `<base_dir>/<runid>/bin/echam/echam6` does exist.

What works is that the runscript with the new `model_dir` is copied to work:
```
cd /work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/esm-piControl2/scripts
awicm_recom_levante_esm-piControl-spinup_wout_talk_restore.run.yaml # old model_dir
awicm_recom_levante_esm-piControl.run.yaml # new model_dir
```

**Comment by pgierz** [comment] 2023-01-04 10:04
Sorry, I'm confused. 

The virtual env functionality (protects your runtime environment) and your model directory (protects your computation) are not connected. They never were, and that was never a design goal...so: What exactly is your problem? Or rather: what do you want to do?

> If the directory .venv_esmtools/ exists, esm_runscripts -U still has no effect on the model binaries, the old already existing binaries are used.

To clarify: virtual env simply installs the esm-tools you currently have into a specific folder, connected to your experiment, and only uses that one during the experiment. It has nothing to do with your model code or compiled binaries. Those anyway are only copied once at the very beginning...

**Comment by chrisdane** [comment] 2023-01-04 10:10
> What exactly is your problem? Or rather: what do you want to do?

see inital post

**Comment by pgierz** [comment] 2023-01-04 10:13
I have seen the initial post, and still do not know what exactly you want to do, hence the question ;-)

What do you think the `-U` should do?

**Comment by chrisdane** [comment] 2023-01-04 10:15
> **Expected behavior**
The new model binaries should be used when submitted with -U.

**Comment by pgierz** [comment] 2023-01-04 10:21
OK, so...why are you changing your model binary in the middle of a run? I can build you a new switch which specifically updates one particular category of files, if that helps. 

@mandresm perhaps we need better documentation of what exactly the `-U` switch does and what it is supposed to do.

**Comment by pgierz** [comment] 2023-01-04 10:28
Have a look here:

https://github.com/esm-tools/esm_tools/blob/8c826c1b53c314a60219cd825a0269d4c6543d84/src/esm_runscripts/cli.py#L131-L147

**Comment by chrisdane** [comment] 2023-01-04 10:38
> why are you changing your model binary in the middle of a run?

This is not the question of this issue.

The issue is that an updated 
```
general:
    model_dir: "/new/model/dir"
```
is ignored by the esm_runscripts, even with `-U`: the old already existing model bins in the experiment directory will be used, and not the new ones from `/new/model/dir`.

**Comment by pgierz** [comment] 2023-01-04 10:54
Agreed, that is not the question here. But it is still a valid question. In my opinion, you **should not** be changing your model binary in the middle of the run. That is a) difficult to reproduce in a clean way and b) difficult to explain to someone outside (e.g. me. If someone told me they changed their model in the middle of an experiment, I would reject the paper immediately).

Does the extended switch help you at all?

**Comment by chrisdane** [comment] 2023-01-04 11:00
> Agreed, that is not the question here. But it is still a valid question. In my opinion, you should not be changing your model binary in the middle of the run. That is a) difficult to reproduce in a clean way and b) difficult to explain to someone outside (e.g. me. If someone told me they changed their model in the middle of an experiment, I would reject the paper immediately).

I am aware of this but again, this is not the topic here.

> Does the extended switch help you at all?

I am not sure.

I feel that my problem is not understood. Suppose you run some jobs with
```
general:
    compute_time: "04:00:00"
```
in the runscript. Then, after some time, you stop and change the following in the runscript:
```
general:
    compute_time: "00:30:00"
```
You submit the next run with this updated runscript. What will happen? The maximum queue time will be 30 minutes instead of 4 hours. This works as expected.

The same workflow does not work with `general.model_dir`.

**Comment by mandresm** [comment] 2023-01-06 16:58
Hi @chrisdane, I think I know what you mean. Can you check that `general.model_dir` is actually updated in the `<exp_id>/run_<DATE>/config/*finished_config.yaml`? If it is updated then the problem is what I'm writting below. If not, can you provide the path to your experiment, because then there is some weird issue going on.

You can find information about what `-U` does running `esm_runscripts --help`:
```
  -U, --update          [U]date the tools from the current version and the runscript
  --update-filetypes UPDATE_FILETYPES [UPDATE_FILETYPES ...]
                        Updates the requested files from external sources in a currently ongoing simulation. We strongly advise against using this option unless you really know
                        what you are doing.
```

As you can see `-U` option is exclusively for ESM-Tools files and the runscript.

To update the binaries you need to use `--update-filetypes bin`. That should solve your problem.

**Comment by pgierz** [comment] 2023-01-06 17:51
Can someone please confirm if -U works? I'd like to remove my name from the "might not work anymore" comment if it does indeed work. 

If we need better wording for the help, please suggest something via PR

**Comment by mandresm** [comment] 2023-01-08 10:19
`-U` does what `esm_runscripts --help` says it does. So it works. Now the question is if `--update-filetypes bin` solves the problem for @chrisdane.

**Comment by chrisdane** [comment] 2023-01-11 10:58
Sorry for my confusion. Paul, in your reply from January 4 I didn't understand that `--update-filetypes` was already there (and that's why I didn't try it :facepalm:). But if I would have tried it, I would not have known how. Miguels `--update-filetypes bin` was the solution.

However, now I am completely confused:
```
cd /work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/nmltest # levante
# 1) old run with old bin: 
date -r run_26860101-26860131/work/echam6 # Wed Aug  4 16:29:59 CEST 2021
# 2) new run with new `model_dir` in runscript and `esm_runscripts runscript -e nmltest -c`:
date -r run_18500101-18501231/work/echam6 # Wed Jan  4 10:39:52 CET 2023
```
The second echam6 binary is updated without any of `-U` or `--update-filetypes bin`.

**Comment by pgierz** [comment] 2023-01-11 14:40
Hi Chris,

Sorry for the confusion, that code copy/paste came directly from GitHub, but Miguel's wording of what I had meant to say was more elegant ;-). Now, the question I'm left with is how to present such options better. Do we need more workshops? A more verbose handbook? Suggestions are very very welcome!!

To solve your actual binary problem I will have to look tomorrow, I won't get to that today anymore, sorry.

**Closed as completed** 2023-09-18 07:53 UTC
Labels: outdated?
