### ISSUE TITLE
mail_type and mail_user variables have no effect

### ISSUE THREAD

**Issue by nwieters** [esm-tools/esm_tools#232] opened 2020-12-02 14:49 UTC
**Describe the bug**
When setting the variables `mail_type` and `mail_user` in the runscript, it does not have any effect.

**To Reproduce**
```
computer:
    mail_type: ALL
    mail_user: nadine.wieters@awi.de
```
When setting this, no email notification through slurm will be sent.

**Expected behavior**
This way it works:

```
computer:
    mail1: "--mail-type=ALL"
    mail2: "--mail-user=nadine.wieters@awi.de"
```
I receive an email at start and end of my simulation.

But I guess it should work for the variables `mail_type` and `mail_user`.

**System (please complete the following information):**
 - Supercomputer: Ollie
 - Version 5.0.0

**Additional context**

**Comment by nwieters** [comment] 2020-12-03 11:17
I think that the `choose_mail_type:` block in `slurm.yaml` will not be entered at all.

I tried this

```
21 choose_accounting:
22         True:
23                 accounting_flag: "--account=${general.account}"
24 
25 choose_mail_type:
26         True:
27                 mail1:  "--mail-type=ALL"
28         "*":    
29                 mail1:  "--mail-type=${mail_type}"
```
(because it seems to work for accounting),

and set 
```
computer:
     mail_type: True
     mail_user: "nadine.wieters@awi.de"
```
in my runscript, but it doesn't have any effect on the sbatch header.

**Comment by nwieters** [comment] 2020-12-03 14:30
I think that the `choose_mail_type:` part in the `slurm.yaml` will not be entered at all.

I tried the following:
```
 21 choose_accounting:
 22         True:
 23                 accounting_flag: "--account=${general.account}"
 24 
 25 choose_mail_type:
 26         True:
 27                 mail1:  "--mail-type=ALL"
 28         "*":    
 29                 mail1:  "--mail-type=${mail_type}"
```
and set 
```
computer:
     mail_type: True
```
in my runscript, but this also has no impact on sbatch header.

**Comment by nwieters** [comment] 2020-12-07 10:11
Does anybody has an idea why this choose_mail_type is not evaluated and where/how to debug this? Is this part of the esm_parser?

**Comment by denizural** [comment] 2021-03-10 09:00
Hi everyone, 

After the merge (both release and develop):
https://github.com/esm-tools/esm_parser/commit/70ebbb25682e3d76f32106e2e17cc27d22552575

This should no longer be an issue. I tried the following

```yaml
computer:
    mail_type: FAIL
    mail_user: "deniz@foo.com"
```

and the sad file contains:
```bash
#SBATCH --mail-type=FAIL --mail-user=deniz@foo.com
``` 

The changed files in the commit contains comments on how the problem is solved. I am closing this issue now.

**Closed as completed by denizural** 2021-03-10 09:00 UTC
Labels: bug
