### ISSUE TITLE
Where is "branch" set for a model component?

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#1137] opened 2024-02-18 13:57 UTC
Hey all

There are FOCI-OpenIFS version 3.0 and 3.0.1. They are identical, except for one compile key in NEMO. Therefore, when I run `esm_master get-focioifs-3.0.1` ESM-Tools should pull NEMO from the same repo as for `3.0` but a different branch. 

In `nemo.yaml` we set
```python
choose_version: 
   ORCA05_LIM2_KCM_AOW_FS_OASISMCT4:
    requires:
    - nemobasemodel-3.6foci
    branch: esm-tools
    destination: nemo-${nemo.version}/CONFIG/${nemo.version}
    git-repository: https://git.geomar.de/foci/src/nemo_config/${nemo.version}.git
```

That's fine for FOCI-OpenIFS 3.0, but for 3.0.1 I want to pull branch "foci30". 
So in `focioifs.yaml` I set:
```python
nemo:
        choose_general.version:
                "3.0.1":
                        version: "ORCA05_LIM2_KCM_AOW_FS_OASISMCT4"
                        resolution: ORCA05
                        branch: foci30
                "3.0":
                        version: "ORCA05_LIM2_KCM_AOW_FS_OASISMCT4"
                        resolution: ORCA05
```

I would have expected that what is in `focioifs.yaml` overrides settings in `nemo.yaml` and thus switches from branch "esm_tools" to "foci30". 

But then this happens
```bash
(base) glogin7:/scratch/usr/shkjocke/model_test $ esm_master get-focioifs-3.0.1 -c 
    Executing commands in this order:
         mkdir -p focioifs-3.0.1
         cd focioifs-3.0.1
         git clone -b master https://git.geomar.de/foci/src/oasis3-mct5.git oasis
         git clone -b 2.5_r1910 https://git.geomar.de/foci/src/xios.git xios
         git clone -b foci22 https://gitlab.dkrz.de/ec-earth/oifs-43r3.git oifs-43r3-foci22
         chmod 700 -R oifs-43r3-foci22
         git clone -b esm-tools https://git.geomar.de/foci/src/nemo.git nemo-ORCA05_LIM2_KCM_AOW_FS_OASISMCT4
         git clone -b esm-tools https://git.geomar.de/foci/src/nemo_config/ORCA05_LIM2_KCM_AOW_FS_OASISMCT4.git nemo-ORCA05_LIM2_KCM_AOW_FS_OASISMCT4/CONFIG/ORCA05_LIM2_KCM_AOW_FS_OASISMCT4
         git clone -b foci211 https://gitlab.dkrz.de/ec-earth/runoff-mapper.git rnfmap-foci211
         sed -i '/COUPLENEMOECE = /s/.TRUE./.FALSE./g' oifs-43r3-foci22/src/ifs/module/yommcc.F90
         sed -i '/COUPLEFESOM2 = /s/.TRUE./.FALSE./g' oifs-43r3-foci22/src/ifs/module/yommcc.F90
         sed -i '/COUPLENEMOFOCI = /s/.FALSE./.TRUE./g' oifs-43r3-foci22/src/ifs/module/yommcc.F90
         cd ..
esm_master: check mode is activated. Not executing the actions above
```

As you can see, ESM-Tools tries to pull the `esm-tools` branch of NEMO (the one set in`nemo.yaml`) and not `foci30` (set in `focioifs.yaml`). 
I'm really puzzled by this. 
Every version of FOCI-OpenIFS uses the same repo for OpenIFS, but different branches. If I set in `focioifs.yaml` 
```python
oifs:
        choose_general.version:
                "3.0.1":
                        branch: test
```
it will try to pull the branch `test` for 3.0.1. 

Does anyone have any ideas why setting a branch in `focioifs.yaml` does not override what is in `nemo.yaml`? 

Best wishes
Joakim

**Comment by mandresm** [comment] 2024-02-21 13:31
Hi @joakimkjellsson,

I think I understand where the problem is coming from, but I cannot reproduce it exactly because `geomar_dev` does not have the required changes for version `3.0.1`. Can you upload and let me know the name of the branch experiencing these problems?

**Comment by joakimkjellsson** [comment] 2024-02-21 16:23
Hi Miguel

Yes, this is the `geomar_dev` branch. Sorry, I should have mentioned that! 

Does this problem not exist for the `release` branch? That's an odd bug! 

/J

**Comment by mandresm** [comment] 2024-02-21 17:02
Hi @joakimkjellsson,

I was trying on `geomar_dev` but somehow I get this error:

```
esm_master get-focioifs-3.0.1 -c 

No targets found for keyword focioifs-3.0.1. Type 'esm_master' to get a full list
of available targets.
```

If I `grep -r "3\.0\.1" configs` I cannot find a single match for `3.0.1`. I think you might need to commit some changes and push them?

**Comment by joakimkjellsson** [comment] 2024-02-21 17:28
If you pull and checkout branch `focioifs_correct_versions` that should have everything. 

Also, a quick test revealed that if I move the `branch: foci30` out of the `choose` block, then it picks the right branch. 
```python
nemo:
        nproca: ${jpni}
        nprocb: ${jpnj}
        branch: foci30
        choose_general.version:
```

But of course that's not a good solution since we want to be able to choose separate branches for different FOCI-OpenIFS versions...

Somehow, ESM-Tools goes through the choose block and set the correct `version: "ORCA05_LIM2_KCM_AOW_FS_OASISMCT4"`, but not `branch: foci30`. 
Could it be that `branch` is overwritten by something else somewhere? 

/J

**Comment by mandresm** [comment] 2024-02-22 15:08
Hi @joakimkjellsson,

This is how ESM-Tools handles priorities and why this is not working for you:
1. ESM-Tools merges following the hierarchy the variables in `nemo.yaml` and `focioifs.yaml`. That leads to the following state:
```yaml
nemo:
        # From focioifs.yaml
        choose_general.version:
                "3.0.1":
                        version: "ORCA05_LIM2_KCM_AOW_FS_OASISMCT4"
                        resolution: ORCA05
                        branch: foci30
        # From nemo.yaml                        
        choose_version: 
                ORCA05_LIM2_KCM_AOW_FS_OASISMCT4:
                        requires:
                            - nemobasemodel-3.6foci
                        branch: esm-tools
                        destination: nemo-${nemo.version}/CONFIG/${nemo.version}
                        git-repository: https://git.geomar.de/foci/src/nemo_config/${nemo.version}.git
```
2. Now ESM-Tools will try to resolve these two chooses sequentially but it understands that the second one depends on the `nemo.version` that is defined in the first one `general.version`, so first it resolves the first one and while resolving the second one overwrites the value of `branch: foci30` with `esm-tools` value.

I can understand that this is not a nice behaviour. We are working on a feature (provenance) that allows us to understand from which hierarchy level each ESM-Tools value comes from at any point in the code (for example it tells us that `foci30` comes from `focioifs.yaml`, the setup, and `esm-tools` comes from `nemo.yaml`, a component). With this feature we can very easily solve this type of problems.

However, this feature is not yet finished, so here a simple workaround: add a new version of NEMO:
In `nemo.yaml`:
```diff
choose_version: 
   ORCA05_LIM2_KCM_AOW_FS_OASISMCT4:
      requires:
      - nemobasemodel-3.6foci
      branch: esm-tools
      destination: nemo-${nemo.version}/CONFIG/${nemo.version}
      git-repository: https://git.geomar.de/foci/src/nemo_config/${nemo.version}.git
+   ORCA05_LIM2_KCM_AOW_FS_OASISMCT4_foci30:
+     requires:
+     - nemobasemodel-3.6foci
+     branch: "foci30"
+     destination: nemo-${nemo.version}/CONFIG/${nemo.version}
+     git-repository: https://git.geomar.de/foci/src/nemo_config/${nemo.version}.git
```
and in `focioifs.yaml`:
```diff
nemo:
        choose_general.version:
                "3.0.1":
-                        version: "ORCA05_LIM2_KCM_AOW_FS_OASISMCT4"
+                        version: "ORCA05_LIM2_KCM_AOW_FS_OASISMCT4_foci30"
-                        resolution: ORCA05
-                        branch: foci30
```

This solution is in my view not too horrible: the full description of the NEMO version is in the `nemo.yaml`, and the selection of the version for FOCIOIFS is made in `focioifs.yaml`.

Please, let me know if that works. We'll keep you posted with our choose logic improvements pending on the provenance.

**Comment by mandresm** [comment] 2024-04-11 14:08
Hi @joakimkjellsson, did the provisional solution work?

**Closed as completed** 2024-10-21 17:04 UTC
