### ISSUE TITLE
AWICM3 frontiers branch tests failing

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#761] opened 2022-08-02 10:53 UTC
Due to recent updates in the source-code without updating the tools info, the `frontiers` branches are failing the actual tests in ESM-Tools with the following error from FESOM:

```
  3: forrtl: severe (24): end-of-file during read, unit 103, file /work/ollie/mandresm/testing/run/awicm3/awicm3-frontiers-TCO159L91-CORE2_initial/run_20000101-20000101/work/namelist.io, line 19, position 0
  3: Image              PC                Routine            Line        Source             
  3: fesom              00000000008DAB0E  for__io_return        Unknown  Unknown
  3: fesom              0000000000917C8C  for_read_seq_nml      Unknown  Unknown
  3: fesom              0000000000545298  Unknown               Unknown  Unknown
  3: fesom              0000000000540E11  Unknown               Unknown  Unknown
  3: fesom              0000000000469B33  Unknown               Unknown  Unknown
  3: fesom              00000000004107DE  Unknown               Unknown  Unknown
  3: libc-2.17.so       00002AAAB53E3555  __libc_start_main     Unknown  Unknown
  3: fesom              00000000004106E9  Unknown               Unknown  Unknown
```

Input from the developers of this changes is required.

Path to the namelist use for that run: `/work/ollie/mandresm/testing/run$ vim awicm3/awicm3-frontiers-TCO159L91-CORE2_initial/run_20000101-20000101/work/namelist.io`

**Comment by tsemmler05** [comment] 2022-08-22 12:39
This is because hegish added the facility to only output every nth level of 3D FESOM output. Therefore, on this branch, 

&nml_output_settings
    keep_nth_level = 1
/

needs to be added in namelist.io . keep_nth_level = 1 means that every level is kept. The user could decide to only output every nth level. We won't commit this change right now because we detected that with this option some of the output parameters defined in namelist.io are missing from the FESOM output when using this choice. Once hegish will have found the problem hopefully in the next days we will commit the change.

**Comment by tsemmler05** [comment] 2022-08-30 12:30
The problem is fixed - this additional namelist entry needs to be before the entry "&nml_list". This is now committed in the aleph_production branch under namelists/fesom2/2.0/awicm3/DART/namelist.io, in awicm-3-frontiers-xios branch under namelists/fesom2/awicm3/frontiers/namelist.io, and in awicm-3-frontiers branch under namelists/fesom2/awicm3/awicm-3-frontiers/namelist.io. I am just not sure if this change has to be committed also in other namelist subdirectories.

**Comment by mandresm** [comment] 2022-09-15 09:23
Thanks for your insights Tido!

**Closed as completed** 2022-09-16 14:01 UTC
