### ISSUE TITLE
Running AWICM3v-3.1 on JUWELS and FESOM's CMake settings

### ISSUE THREAD

**Issue by mbutzin** [esm-tools/esm_tools#833] opened 2022-10-04 15:19 UTC
I am trying to run AWICM3v-3.1 with resolution TCO95L91 on Juwels. The model quickly crashes with the error message
"ABORT!    1  UPDO3CH: PROBLEM OPENING O3CHEM FILE FOR FIRST MONTH"
As my project is project is hhb20, I looked into the pool directory 
/p/project/chhb20/jstreffi/input/oifs-43r3/TCO95L91   
to locate the ozone data and discovered that the directories 95_4 and 95l_4 are symbolic links pointing to 
/p/project/chhb19/streffing1/input/oifs-43r3/43r3/climate/95_4/ 
I presume that the model crashes because I do not have the permission to access files belonging to projects other than hhb20. Is it possible to reorganize the pool directories?

Another, unrelated but nonetheless puzzling observation (not only on Juwels but also on Ollie and Levante):
In the FESOM model directory of AWICM3 (e.g. model_codes/awicm3-v3.1/fesom-2.0/) CMakeLists.txt reads:
set(FESOM_COUPLED OFF CACHE BOOL "compile fesom standalone or with oasis support (i.e. coupled)")
set(OIFS_COUPLED OFF CACHE BOOL "compile fesom coupled to OpenIFS. (Also needs FESOM_COUPLED to work)")
I would expect that the compilation would result in two uncoupled models. What am I missing here?

**Comment by mandresm** [comment] 2022-10-05 08:57
> Another, unrelated but nonetheless puzzling observation (not only on Juwels but also on Ollie and Levante):
> In the FESOM model directory of AWICM3 (e.g. model_codes/awicm3-v3.1/fesom-2.0/) CMakeLists.txt reads:
> set(FESOM_COUPLED OFF CACHE BOOL "compile fesom standalone or with oasis support (i.e. coupled)")
> set(OIFS_COUPLED OFF CACHE BOOL "compile fesom coupled to OpenIFS. (Also needs FESOM_COUPLED to work)")
> I would expect that the compilation would result in two uncoupled models. What am I missing here?

Hi Martin,

I can answer for that point. This was a recommendation from @hegish: changing the source code automatically through ESM-Tools is not advised, not even the `CMakeLists.txt`.

Instead, we set the the `COUPLE` variables during the cmake command, so if you look at the compilation script `awicm3-v3.1/comp-fesom-2.0-awicm-3.1_script.sh` you'll see this line at the end of the file:
```
mkdir -p build; cd build; cmake -DOIFS_COUPLED=ON -DFESOM_COUPLED=ON ..;   make install -j `nproc --all`
```

So both `OIFS_COUPLED` and `FESOM_COUPLED` are set to `ON`. You can check that that is true if you look at this file and look for those variables: `awicm3-v3.1/fesom-2.0/build/CMakeCache.txt`

**Comment by mandresm** [comment] 2022-10-06 09:15
> I am trying to run AWICM3v-3.1 with resolution TCO95L91 on Juwels. The model quickly crashes with the error message
> "ABORT! 1 UPDO3CH: PROBLEM OPENING O3CHEM FILE FOR FIRST MONTH"
> As my project is project is hhb20, I looked into the pool directory
> /p/project/chhb20/jstreffi/input/oifs-43r3/TCO95L91
> to locate the ozone data and discovered that the directories 95_4 and 95l_4 are symbolic links pointing to
> /p/project/chhb19/streffing1/input/oifs-43r3/43r3/climate/95_4/
> I presume that the model crashes because I do not have the permission to access files belonging to projects other than hhb20. Is it possible to reorganize the pool directories?

I can also reply to this with what I know (@JanStreffing please feel free to add suggestions): unfortunately, Juwels doesn't have a pool that can be read from all users, and it seems that they are not willing to set that up in the future for security reasons? I thought the solution until now was to have a copy of the input files in each project folder, so I am a bit surprise that the files in `hhb20` are links to `hhb19`. I guess the solution here would be to do an actual copy of those files. It makes no sense to have multiple copies of this files spread among the projects, but that's the only solution we could come up with with the current limitations of the Juwels admins.

**Comment by JanStreffing** [comment] 2022-10-06 09:43
I turned the link into an actual copy. It seems that when I copied some of the links inside were still pointing to the original.

**Comment by JanStreffing** [comment] 2022-10-06 09:46
Regarding the second question of `FESOM_COUPLED OFF` and `OIFS_COUPLED OFF` These are set to ON at compile time by esm_tools with a cmake flag: `cmake -DOIFS_COUPLED=ON -DFESOM_COUPLED=ON ` This way the defaults need not be touched. You can find these flags in the c`omp-fesom-2.0-master_script.sh`

**Comment by mandresm** [comment] 2022-10-06 09:55
@mbutzin, feel free to close this issue whenever you test that the problem is solvde

**Comment by mbutzin** [comment] 2022-10-06 12:58
> I turned the link into an actual copy. It seems that when I copied some of the links inside were still pointing to the original.

Unfortunately, the model still crashes with the same error message related to ozone (see also
/p/scratch/chhb20/butzin1/runtime/awicm3-v3.1/test_initial_2/log):

144:  ABORT!    1  UPDO3CH: PROBLEM OPENING O3CHEM FILE FOR FIRST MONTH
144: MPL_ABORT: CALLED FROM PROCESSOR      1 THRD     1
144:  MPL_ABORT: THRD           1
144:   UPDO3CH: PROBLEM OPENING O3CHEM FILE FOR FIRST MONTH
144:  SDL_TRACEBACK: Calling INTEL_TRBK, THRD =            1
144:  Process            1  thread            1  calling linux_trbk from intel_trbk()
144:   [LinuxTraceBack@/p/home/jusers/butzin1/juwels/model_codes/awicm3-v3.1/oifs-43r3/src/ifsaux/utilities/linuxtrbk.c:240] Backtrace(s) for program './oifs' : sigcontextptr=0x7fff6a5c2680

Is there a way to run the model in a debugging / traceback mode?

**Comment by mandresm** [comment] 2022-10-06 13:16
@JanStreffing, I think ESM-Tools (at least for Martin's simulation) is trying to copy the data from `/p/project/chhb20/jstreffi/input//oifs-43r3/43r3/climate/95_l4/` and that folder does not exist. If you compare `/p/project/chhb20/jstreffi/input//oifs-43r3/43r3/climate` and `/p/project/chhb19/jstreffi/input//oifs-43r3/43r3/climate/` you'll see that many folders are missing in the former.

**Comment by JanStreffing** [comment] 2022-10-06 13:18
Maybe the problem was never a link, but that the folder on the chhb20 project was out of date:
```
drwxr-sr-x 8 streffing1 chhb20 4096 Nov 23  2021 319_3
drwxr-sr-x 8 streffing1 chhb20 4096 Nov 23  2021 319l_4
drwxr-sr-x 5 streffing1 chhb20 4096 Nov 23  2021 63_2
drwxr-sr-x 8 streffing1 chhb20 4096 Nov 23  2021 319_4
drwxr-sr-x 8 streffing1 chhb20 4096 Nov 23  2021 159_4
drwxr-sr-x 5 streffing1 chhb20 4096 Nov 23  2021 511l_2
drwxr-sr-x 8 streffing1 chhb20 4096 Nov 23  2021 319l_2
drwxr-sr-x 5 streffing1 chhb20 4096 Nov 23  2021 799l_2
drwxr-sr-x 8 streffing1 chhb20 4096 Nov 23  2021 159l_4
drwxr-sr-x 5 streffing1 chhb20 4096 Nov 23  2021 95l_2
drwxr-sr-x 5 streffing1 chhb20 4096 Nov 23  2021 255l_2
drwxr-sr-x 5 streffing1 chhb20 4096 Nov 23  2021 1279l_2
drwxr-sr-x 8 streffing1 chhb20 4096 Nov 23  2021 159_3
drwxr-sr-x 8 streffing1 chhb20 4096 Nov 23  2021 159l_2
```

its missing some folders, including 95_4 compared to the chbb19 one:

```
drwxr-sr-x 5 streffing1 chhb19 4096 Apr 22  2020 799l_2
drwxr-xr-x 8 streffing1 chhb19 4096 Apr 22  2020 159l_4
drwxr-sr-x 5 streffing1 chhb19 4096 Apr 22  2020 511l_2
drwxr-xr-x 8 streffing1 chhb19 4096 Apr 22  2020 319l_2
drwxr-xr-x 8 streffing1 chhb19 4096 Apr 22  2020 319_3
drwxr-xr-x 8 streffing1 chhb19 4096 Apr 22  2020 159l_2
drwxr-xr-x 8 streffing1 chhb19 4096 Apr 22  2020 159_3
drwxr-sr-x 5 streffing1 chhb19 4096 Apr 22  2020 63_2
drwxr-sr-x 5 streffing1 chhb19 4096 Apr 22  2020 255l_2
drwxr-sr-x 5 streffing1 chhb19 4096 Apr 22  2020 1279l_2
drwxr-xr-x 8 streffing1 chhb19 4096 Apr 22  2020 159_4
drwxr-xr-x 8 streffing1 chhb19 4096 Sep 13  2021 319_4
drwxr-xr-x 8 streffing1 chhb19 4096 Sep 13  2021 319l_4
drwxr-s--- 8 streffing1 chhb19 4096 Nov 30  2021 639_3
drwxr-s--- 8 streffing1 chhb19 4096 Nov 30  2021 639l_2
drwxr-s--- 8 streffing1 chhb19 4096 Nov 30  2021 639_4
drwxr-s--- 8 streffing1 chhb19 4096 Nov 30  2021 95_3
drwxr-s--- 8 streffing1 chhb19 4096 Nov 30  2021 95l_2
drwxr-s--- 8 streffing1 chhb19 4096 Oct  6 11:41 95l_4
drwxr-s--- 9 streffing1 chhb19 4096 Oct  6 11:41 95_4
```

Did the esm_tools complain in any way about this missing folder when you submitted to job? Can you give it another try?
I have copied over the missing ones.

**Comment by mandresm** [comment] 2022-10-06 13:21
A side note: ESM-Tools doesn't complain about wildcarded set of files, and that's what the o3_data files are (it will complain in the future with the refactored filedicts), so I would expect that Martin got no notification of missing files.

**Comment by JanStreffing** [comment] 2022-10-06 13:22
makes sense. can't check if it's there if we don't tell esm_tools what's supposed to be there  ;-)
We could check if the folder exists perhaps..

**Comment by mandresm** [comment] 2022-10-06 13:24
or if at least one coinciding file is found. I just added this as a ticket in the Filedicts project so that we don't forget about it.

**Comment by mbutzin** [comment] 2022-10-06 14:06
> Maybe the problem was never a link, but that the folder on the chhb20 project was out of date:
> Did the esm_tools complain in any way about this missing folder when you submitted to job? Can you give it another try? I have copied over the missing ones.

Thanks - this solved the problem! 
And @mandresm is right that there was no notification of missing files.

**Closed as completed** 2022-10-06 14:07 UTC
