### ISSUE TITLE
AWI-CM 2: Nothing in outdata for FESOM2

### ISSUE THREAD

**Issue by nwieters** [esm-tools/esm_tools#19] opened 2020-04-24 08:58 UTC
I ran a simulation with AWI-CM 2, monthly restart. I get output except for Fesom2 in outdata. It stays in the work folder of each run_... folder.

esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar : 3.0.1
esm_database : 3.1.3
esm_environment : 3.0.2
esm_master : 3.2.1
esm_parser : 3.0.3
esm_profile : 3.0.0
esm_rcfile : 3.0.1
esm_runscripts : 3.2.7
esm_tools : 3.1.4
esm_version_checker : 3.2.4

**Comment by pgierz** [comment] 2020-05-18 16:12
I also have this problem, looks there is a problem in the FESOM 2 Yaml files. @dbarbi, maybe this is a good practice exercise for some of the new guys?

**Comment by mandresm** [comment] 2020-05-22 13:25
The problem is solved now and the necessary changes in fesom-2.0.yaml merged to the release. However, these changes need of new functionalities implemented by @dbarbi in the esm_runscripts, oifs_stuff branch, so I'll wait @dbarbi  to merge oifs_stuff to close this issue.

In the mean time bump version 4.0.5 offers a solution that is not optimal, but works without the changes in esm_runscripts.

**Closed as completed** 2020-09-03 10:44 UTC
Labels: bug, help wanted
