### ISSUE TITLE
Wrong jsbach files for no-dynveg and unnecessary streams

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#174] opened 2020-10-21 14:10 UTC
Vanessa (AWI Bremerhaven) reported the following bug via email.

**Describe the bug**
I am using ECHAM T127, but without dynamic vegetation. But instead of only using jsbach_T127GLOB_11tiles_5layers_1850_no-dynveg.nc , it still searches for jsbach_T127GLOB_11tiles_1851.nc. I know, it takes the info from the config file for jsbach, but I am unsure how to change it. I included dynamic_vegetations: false in the yaml file, but that does not seem to be enough.

Secondly, I do not include the nitrogen cycle, How do I switch it off?

**To Reproduce**
Using the following runscript:
```
general:
     setup_name: "awicm"
     account: b0246
     compute_time: "00:25:00"
     expid: "hist1_old_mesh"
awicm:
     version: "CMIP6"
     scenario: "HIST"
     post_processing: 0
     initial_date: "1851-01-01"
     final_date: "1851-02-01"
     model_dir: /pf/a/a270152/model_codes/awicm-CMIP6/
     base_dir: /work/ab0246/a270152/esm_yaml_test/
     pool_dir: /pool/data/
     resolution: T127
     nyear: 0
     nmonth: 1
fesom:
     lresume: 1 
     pool_dir: /work/bm0944/input/
     mesh_dir: /pool/data/AWICM/FESOM1/MESHES/glob/
     resolution: GLOB
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/fesom/
     ini_parent_date: 18501231
     ini_parent_exp_id: "hist1"
     first_initial_year: 1850
     restart_rate: 1
     restart_first: 1
     restart_unit: "m" 
     further_reading: "fesom_output_control.yaml"
echam:
     resolution: "T127"
     lresume: 1
     scenario: "HIST" 
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/echam/
     ini_parent_date: 18501231
     ini_parent_exp_id: "hist1"
     dataset: r0007
     nproca: 24
     nprocb: 48
     disturbed_years: 2013
     disturbance: 1.00001
oasis3mct:
     lresume: 1
#     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/input/oasis3mct/
     ini_restart_dir: /work/ba1150/a270147/hist1_oasis_restart/
     ini_parent_date: 18501231
     ini_parent_exp_id: "hist1"
jsbach:
    ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/jsbach/
    dataset: r0009
    dynamic_vegetations: false

hdmodel:
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/hdmodel/
```

**Expected behavior**
ESM-Tools loads the correct files when `dynamic_vegetations` is set to `false` and that streams are selected based on the user's choices.

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version [Please run `esm_versions check`]

**Additional context**
Experiment type restart AWICM-CMIP6

**Comment by mandresm** [comment] 2020-10-21 14:14
**Provisional solution**
Add the following to the runscript:
```
    streams:
        - jsbach
        - jsbid
        - yasso
        - surf
        - land
    add_forcing_sources:
        "cover_fract_HIST":
            "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_1850${jsbachnc_file_ending}.nc"
```

I'll be working asap on a fix.

**Comment by mandresm** [comment] 2020-10-21 14:21
@jobo95 pointed out via email:
"Also a minor point what I think might be a bit confusing is that it is e.g. reporting and looking for these  dynamical vegetation missing files in the beginning, although they are not used at all when  dynamical vegetation is turned off..."

I think this is relevant to this issue so I included here. @jobo95 , feel free to add more details about it.

**Comment by ghost** [comment] 2020-10-21 16:44
> 
> 
> @jobo95 pointed out via email:
> "Also a minor point what I think might be a bit confusing is that it is e.g. reporting and looking for these dynamical vegetation missing files in the beginning, although they are not used at all when dynamical vegetation is turned off..."
> 
> I think this is relevant to this issue so I included here. @jobo95 , feel free to add more details about it.

Hi, in my case I started an ECHAM standalone simulation with e.g. a runscript of the following form: 

```
general:
        setup_name: echam
        account: bb1152
        compute_time: "08:00:00"
        post_time: "01:00:00"

        initial_date: "1850-01-01"
        final_date: "1850-03-31"

        base_dir: "/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments"
        model_dir: "/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/echam-6.3.04p1"

        nyear: 0
        nmonth: 1

echam:
        scenario: "PI-CTRL"
        version: "6.3.04p1"
        bin_dir: ${model_dir}/src/echam/bin/HICE_thickness_sara
        namelist_dir: "/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/esm_tools/namelists/echam/6.3.04p1/Johannes"
        #pool_dir: /pool/data
        resolution: T127
        ocean_resolution: TP04
        levels: L95

        lresume: False
        #restart_unit: "years"
        restart_unit: "months"
        restart_rate: 1
        restart_first: 1
        nproca: 24
        nprocb: 48

        add_forcing_sources:
                pisst: /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/T127_HadNOAAOI_SST_LAMO.nc
                pisic: /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/T127_HadNOAAOI_SIC_HICE.nc


jsbach:
        namelist_dir: "/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/esm_tools/namelists/jsbach/3.20/Johannes"
        dynamic_vegetations: False
        dataset: r0009
        #dynveg: False

```

and got some reported missing forcing files:

```
MISSING FILES:
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//landuse_harvest.1850.nc:
        --> /pool/data/JSBACH/input/r0009/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1850.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//landuse_harvest.1849.nc:
        --> /pool/data/JSBACH/input/r0009/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1850.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//landuse_harvest.1851.nc:
        --> /pool/data/JSBACH/input/r0009/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1850.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//a_nd_file.nc:
        --> /pool/data/JSBACH/input/r0009/T127/spitfire/a_nd_T127.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//lightning.nc:
        --> /pool/data/JSBACH/input/r0009/T127/spitfire/LISOTD_HRMC_V2.2_T127.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//population_density.nc:
        --> /pool/data/JSBACH/input/r0009/T127/spitfire/population_density_HYDE_T127.nc
```

I mean, when looking into the JSBACH config file:

```
choose_version:

.........

"3.20":
                dataset: r0010
                choose_dynamic_vegetations:
                        true:
                                namelist_dir: "${general.esm_namelist_dir}/jsbach/${version}/${echam.scenario}/dynveg"
                                dynveg: "_dynveg"
                                jsbachnc_file_ending: "${dynveg_file_ending}"
                        false:
                                namelist_dir: "${general.esm_namelist_dir}/jsbach/${version}/${echam.scenario}/no_dynveg"
                                jsbachnc_file_ending: "${no_dynveg_file_ending}"
                                dynveg: "_no_dynveg"
                choose_echam.scenario:
                        PI-CTRL:
                                add_input_files:
                                        jsbach: jsbach_1850
                                forcing_files:
                                        LU: LU_1850
                                        LU_trans: LU_trans_none
                                        Ndepo: Ndepo_1850
                                        a_nd_file: a_nd_file
                                        lightning: lightning
                                        popdens: popdens
 
........

HIST:
                                add_input_files:
                                        jsbach: jsbach_1850
                                forcing_files:
                                        LU: LU_HIST
                                        LU_trans: LU_trans_none
                                        cover_fract: cover_fract_HIST
```

for my PI-CTRL scenario it's just looking for the forcing files stated there (and doesn't find some of them). But I do not see where it distinguishes bewtween dynamic and non-dynamic vegetation. In my case it's not finding these forcing files in the paths,and according to the ECHAM docs dynamic vegetation should only be used when `USEDYNVEG= .TRUE` is explicitely set in the namelist (which is not the case at least in my case). So I guess finally everthing is fine, but it's still kind of confusing ...   As I am also lacking knowledge about JSBACH and its docs, I am currently not sure which (or if) data from which forcing files should be used for non-dynamical vegetation...

In Vanessa's HIST scenario it's just looking for this `jsbach_T127GLOB_11tiles_1851.nc ` forcing file as it's defined in the jsbach.dataset file fwhen starting 1851: 

```
input_sources:
        lctlib: "${echam.model_dir}/lctlib_nlct21.def"
        "jsbach_1850": "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_5layers_1850${jsbachnc_file_ending}.nc"
        "jsbach_1976": "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_5layers_1850${jsbachnc_file_ending}.nc"

.....

forcing_sources:
        "LU_1850": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc"
        "LU_1950": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1950.nc"
        "LU_HIST":
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc":
                        to: 1850
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                        from: 1851
        "cover_fract_HIST":
               "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_1850.nc":
                        to: 1850
               "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_@YEAR@.nc":
                        from: 1851
        "LU_trans_none": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/no_LUH_transitions_${echam.resolution}.nc"
```

Normally, it should also look for e.g. this `LUH_harvest_T127_185?.nc` forcing file hist scenario, nor? 

 `jsbach_T127GLOB_11tiles_5layers_1850_no-dynveg.nc` should be an input file, so should have nothing to do with the forcing file stated above..

**Comment by ghost** [comment] 2020-10-21 18:13
> `jsbach_T127GLOB_11tiles_5layers_1850_no-dynveg.nc` should be an input file, so should have nothing to do with the forcing file stated above..

Okay, I think this statement I got a bit wrong ..

**Comment by vkolatschek** [comment] 2020-10-26 18:34
If I understood the comments above correctly, the model will not try to use theses dynamic vegetation files even though it lists the files as missing? Could I then just ignore the missing files?

**Comment by mandresm** [comment] 2020-10-27 07:25
@vkolatschek , that is correct, as long as it is copying `jsbach_T127GLOB_11tiles_5layers_1850_no-dynveg.nc` you should be fine.

**Comment by dbarbi** [comment] 2020-10-27 09:02
Hi Vanessa, I took over the issue and am currently looking into it. I will get back at you later today.

Hi again,
so, actually the jsbach.nc file that was taken was the correct one, but the cover_fract files weren't, that confiused me a bit. I wrote a hotfix (branch hotfix/issue174 in esm_tools, please get that by typing 
    git fetch
    git checkout hotfix/issue174
in the esm_tools folder.
I can't really test it right now as mistral is still down, please let me know if it works. Looks sensible on ollie though.

**Comment by vkolatschek** [comment] 2020-10-28 09:13
I tried the fix, and it worked. It does not list  jsbach_T127GLOB_11tiles_1851.nc as missing any longer, except for the cover_fract_... file.
And I am now missing nearly the same files as @jobo95:
```
MISSING FILES:
--  /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/forcing/jsbach//landuse_harvest.1851.nc: 
        --> /pool/data/JSBACH/input/r0009/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1851.nc
--  /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/forcing/jsbach//landuse_harvest.1850.nc: 
        --> /pool/data/JSBACH/input/r0009/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1850.nc
--  /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/forcing/jsbach//cover_fract.1851.nc: 
        --> /pool/data/AWICM/FESOM1/MESHES/glob//tarfilesT127/input/jsbach/cover_fract_T127GLOB_11tiles_1851.nc
--  /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/restart/jsbac/restart_hist1_old_mesh_land.nc: 
        --> /work/bk0988/awicm/a270062/AWICM/hist1/restart/jsbach//restart_hist1_land_18501231.nc
--  /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/work//landuse_harvest.1851.nc: 
        --> /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/forcing/jsbach//landuse_harvest.1851.nc
--  /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/work//landuse_harvest.1850.nc: 
        --> /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/forcing/jsbach//landuse_harvest.1850.nc
--  /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/work//cover_fract.1851.nc: 
        --> /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/forcing/jsbach//cover_fract.1851.nc
--  /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/work//restart_hist1_old_mesh_land.nc: 
        --> /work/ba1150/a270147/awicm-CMIP6//hist1_old_mesh/run_18510101-18510131/restart/jsbach//restart_hist1_old_mesh_land.nc
```

**Comment by dbarbi** [comment] 2020-10-28 10:14
Ok, I just checked that. There is two issues here, none of which is esm_tools related:

- /pool/data/AWICM/FESOM1/MESHES/glob/       doesn't contain any cover_fract files (nor any other files needed for dynamic vegetation). This is a choice of the FESOM developers, who in general don't care for dynamic vegetation (hence the difference between AWICM and AWIESM...)

- /pool/data/JSBACH/input/r0009/T127/        also doesn't contain the files you want, like hist_harvest. They exist in T63 though. This must be the choice of the echam developers.

Your options are to ask the FESOM developers (especially Thomas Rackow) for the cover_fract etc. files, I think he has something in his home folder. For the JSBACH input I don't know - maybe there is something in the r0010 dataset?

**Comment by vkolatschek** [comment] 2020-11-02 11:54
- Yes, the cover_fract_T127_11tiles_*.nc files are indeed in the r0010 dataset, so I changed it. 

- The problem is that according to the jsbach.datasets.yaml the path is:

```
"cover_fract_HIST":
                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_1850.nc":
                        to: 1850
                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_@YEAR@.nc":
                        from: 1851

```
This translates to: /pool/data/JSBACH/input/r0010/T127/land_use_maps/cover_fract_T127_11tiles_1850.nc

But instead the esm-tools seem to replace the path with /pool/data/AWICM/FESOM1/MESHES/glob/ and I don't know where it does that.

**Comment by dbarbi** [comment] 2020-11-02 12:00
That is indeed desired behaviour. The problem is that ocean and land surface model need to agree on the location of the coasts, thats why the JSBACH-files are depending on the ocean resolution. So for every ocean grid of FESOM there are matching JSBACH files, in the fesom mesh folder. So far, so good.
What is really a horrible situation is that this has been done inconsistently, so for example all the meshes in /pool/data/AWICM/FESOM1 only contain JSBACH files for simulations WITHOUT dynamic vegetation (so no cover_fract). I think that in Thomas Rackows personal home folder on mistral there are some meshes INCLUDING the files for dynamic vegetation, hence my suggestion to contact him.

**Comment by vkolatschek** [comment] 2020-11-02 13:00
Ok, I understand that the coast lines have to be identical. But is it still possible to define the path for the cover_fract-files separatly? (It is, after all, already in the configuration files for jsbach) I ask, because later on, I will change some parts of the mesh (without effecting the coast line), and then the paths to the mesh and the cover_fract-files will be different.

**Comment by dbarbi** [comment] 2020-11-03 08:25
OK, after the following info from Tido/Thomas: 

> Tido hat recht, in neueren Versionen von JSBACH/ECHAM6 müssen die cover_fract-Dateien nicht mehr an die Ozeanauflösung 
> angepasst werden. Das ist eine Änderung vom MPI. Zum Beispiel die CMIP6 Läufe sind mit den allgemeingültigen cover_fract Dateien gelaufen, 
> die wir dann vom MPI aus dem /pool übernommen haben. Mag sein, dass Tido und ich das im CMIP-Zeitdruck zusammengehackt haben, aber 
> dass das noch nicht den Weg in die ESM Tools gefunden hat.
> 
> Bei den älteren Versionen (nicht sicher, ob das <r0010 ist) war diese Anpassung aber notwendig (am MPI wurde das genauso gehandhabt für deren Gitter),
> daher haben wir für jedes neue FESOM-Gitter auch die entsprechenden cover_fract-Dateien immer anlegen müssen.
> 
> Die Initialisierungsdateien von jsbach sind noch immer vom jeweiligen Ozeangitter abhänging und haben dessen Namen im Dateinamen. Diese hatte ich
> immer im Meshordner abgelegt, da sie ja zu jedem Gitter angelegt werden müssen. In Zukunft wollen wir das ja vielleicht anders machen und diese Dateien separat ablegen (auf github beispielsweise), aber dennoch brauchen wir diese Dateien für jedes Gitter. Auch das ist am MPI so, dort heißen die Gitter zum Beispiel TP06 oder GR15 und du findest diese Namen in vielen JSBACH-Dateinamen im /pool am DKRZ.

I pushed a commit to hotfix/issue174 in esm_tools. Please try it.

**Comment by vkolatschek** [comment] 2020-11-03 11:10
Yes, that worked. It does not replace the path to the cover_fract_* file with the path to the mesh anymore.

**Comment by dbarbi** [comment] 2020-11-03 13:18
Is your issue solved then? Can I close it?

**Comment by vkolatschek** [comment] 2020-11-03 13:53
I just realized I have one small question. If It does not use dynamic vegetations, why is it trying to find the information on landuse (landuse_harvest)? Can I just ignore those missing files?

**Comment by vkolatschek** [comment] 2020-11-27 12:17
I think, you can close this issue.

**Closed as completed** 2020-11-30 15:13 UTC
Labels: fix waits for testing
